#!/bin/bash

case "${1:-}" in
  install)
    docker-compose run --build --rm php composer install
    ;;
  composer)
    shift
    docker-compose run --rm php composer "$@"
    ;;
  bundle|build)
    shift
    ./bundle.sh "${1:-all}"
    ;;
  ""|--help|help)
    echo
    echo "Usage: run ACTION [OPTIONS]"
    echo
    echo "Development utility wrapper for [docker-compose]."
    echo
    echo "Actions:"
    echo "    install         Installs local packages (composer install)"
    echo "    composer        Run composer command"
    echo "    build           Bundles all OAS sources and generates final OAS build files, for validation and code-generation purpose"
    echo "    help            This help"
    echo
    ;;
esac
