## AQL [/definition/aql]

Management of stored (registered) AQLs in the system.

### List stored AQLs [GET /definition/aql/{id}]

List all available stored AQLs in the system

+ Parameters

    + id (string, optional) - list only version of the AQL with id

+ Response 200 (application/json) 

    `200 OK` is returned when the resources are successfully retrieved.

    + Body

            [
                {
                    "id": "labs",
                    "version": "1.0.1",
                    "aql": "SELECT c FROM EHR e[ehr_id/value=:ehr_id] CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS OBSERVATION o[openEHR-EHR-OBSERVATION.laboratory_test.v0]"
                },
                {
                    "id": "vitals",
                    "version": "2.7.9",
                    "aql": "SELECT c FROM EHR e[ehr_id/value=:ehr_id] CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] WHERE c/name/value = 'Vitals'"
                }
            ]

### Create stored AQL [PUT /definition/aql/{id}]

+ Parameters

    + id (string) - the id under which AQL will be available for execution (GET /query/{id})

+ Request
    
    + Body 

            {
                "version": "2.1.0",
                "aql": "SELECT c FROM EHR e[ehr_id/value=:ehr_id] CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] CONTAINS OBSERVATION o[openEHR-EHR-OBSERVATION.laboratory_test.v0]"
            }

+ Response 201 (application/json) 

    `201 Created` is returned when the guide has been successfully uploaded to the server.

    + Headers

            Location: /definition/aql/{id}/{version}


+ Response 400 

    `400 Bad Request` is returned when the server was unable to create a new stored AQL, could be due to incorrect request body (could not be parsed, etc)

    + Body 

+ Response 409

    `409 Conflict` is returned when a stored AQL with id and version already exists.

    + Body

### Get stored AQL [GET /definition/aql/{id}/{version_pattern}]

+ Parameters

    + id (string) - AQL id
    + version_pattern (string, optional) - SEMVER version pattern. This can be a complete version (i.e. 1.7.1) or partial
    i.e. (1.0) in which case the latest version with given prefix is returned.

+ Response 200 (application/json)
    `200 OK` is returned when the stored AQL is successfully retrieved.

    + Body

                {
                    "id": "vitals",
                    "version": "2.1.0",
                    "aql": "SELECT c FROM EHR e[ehr_id/value=:ehr_id] CONTAINS COMPOSITION c[openEHR-EHR-COMPOSITION.encounter.v1] WHERE c/name/value = 'Vitals'"
                }

+ Response 404 (application/json)
    `404 Not Found` is returned when the stored AQL with supplied id doesn't exist.

    + Body

### Delete stored AQL [DELETE /definition/aql/{id}/{version}]

+ Parameters

    + id (string) - AQL id
    + version (string) - SEMVER version

+ Response 204 (application/json)
    `204 No content` is returned when the stored AQL was successfully deleted.

    + Body

+ Response 404 (application/json)
    `404 Not Found` is returned when the stored AQL with supplied id doesn't exist.

    + Body

