## Query [/query]

### Execute stored query [GET /query/{id}{?param1,param2}]

Execute a stored query with the supplied id.

NOTE: we might add a header to indicate which EHR to execute against to
allow systems that need to route based of EHR id to do so without having
to analyze the request body.

+ Parameters
    + id - Id of the stored query to be executed
    + param1 (optional) - query parameter 1
    + param2 (optional) - query parameter 2

+ Response 200 (application/json)
    
        {
           /* Se discussion on resultset in overview */
        }

### Execute stored query [POST /query/{id}]

Execute a stored query.

NOTE: we might add a header to indicate which EHR to execute against to
allow systems that need to route based of EHR id to do so without having
to analyze the request body.

+ Parameters
    + id - Id of the stored query to be executed

+ Request (application/json)

    + Body

            {
                "aql_parameters": [
                    {
                        "parameter-x-name": "paramater-x-value",
                        "parameter-y-name": "parameter-y-value"
                    }
                ],
                "offset": NUMBER_TO_START_FROM,
                "fetch": NUMBER_TO_FETCH,
                "composition_uids": ["<object_id>"], // filter on the given compositions uids
                "ehr_ids": ["<ehr_id>"] // filter on the given ehr_ids
            }

+ Response 200 (application/json)

         {
           /* Se discussion on resultset in overview */
         }

### Execute ad-hoc AQL query [POST /query/aql]

Execute an AQL query.

NOTE: we might add a header to indicate which EHR to execute against to
allow systems that need to route based of EHR id to do so without having
to analyze the request body.

+ Request (application/json)

    + Body

            {
                "aql": "<the aql to be performed>",
                "aql_parameters": [{
                    "parameter-x-name": "paramater-x-value",
                    "parameter-y-name": "parameter-y-value"
                }],
                "offset": NUMBER_TO_START_FROM,
                "fetch": NUMBER_TO_FETCH,
                "composition_uids": ["<object_id>"], // filter on the given compositions uids
                "ehr_ids": ["<ehr_id>"] // filter on the given ehr_ids
            }

+ Response 200 (application/json)

         {
           /* Se discussion on resultset in overview */
         }
