## CONTRIBUTION [/ehr/{ehr_id}/contribution]

Management of [CONTRIBUTION](https://specifications.openehr.org/releases/RM/latest/common.html#_contribution_class) resources.  


### Create contribution [POST /ehr/{ehr_id}/contribution]

We will use the relaxed CONTRIBUTION XSD with the following attributes optional:
 - time_committed: server will always set it
 - UID: if provided will be accepted unless it is already used in which case an error will be returned
 - system_id: where provided will be validated

+ Parameters 

    + ehr_id: `7d44b88c-4199-4bad-97dc-d78268e01398` (string) - EHR identifier 
        taken from EHR.ehr_id.value

+ Request (application/json) 

    + Body

            {
                "versions": [
                    {
                        "data": {
                            /* optional JSON serialized COMPOSITION, FOLDER or EHR_STATUS object */
                        },
                        "preceding_version_uid": "<optional string>", 
                        "signature": "<optional string>", 
                        "lifecycle_state": 0,
                        "commit_audit": {
                            "change_type": {},
                            "description": {},
                            "committer": {
                                /* optional structure - will use the outer committer if absent */
                            }
                        }
                    }
                ],
                "audit":{
                    "committer":{
                        "name": "<optional identifier of the committer>"  ,
                        "external_ref":{
                            "namespace": "demographic",
                            "type": "PERSON",
                            "id":{
                                "value": "<OBJECT_ID>"
                            }
                        }
                    }
                }
            }

    + Headers

            Prefer: return={representation|minimal}

+ Response 201 

    `201 Created` is returned when the CONTRIBUTION was created. 
    Content body is only returned when `Prefer` header has `return=representation` otherwise only headers are returned. 

    + Headers

            Location: {baseUrl}/ehr/7d44b88c-4199-4bad-97dc-d78268e01398/contribution/0826851c-c4c2-4d61-92b9-410fb8275ff0
            ETag: "0826851c-c4c2-4d61-92b9-410fb8275ff0"

    + Body 

            {
                "_type": "CONTRIBUTION",
                "uid": {
                    "value": "0826851c-c4c2-4d61-92b9-410fb8275ff0"
                },
                "versions": [
                    {
                        "_type": "OBJECT_REF",
                        "id": {
                            "_type": "OBJECT_VERSION_ID",
                            "value": "fb458d9c-1323-42bc-b7f8-787f3660a0b5::91215053-854b-45b8-bb2a-3b0d255858d1::1"
                        },
                        "namespace": "local",
                        "type": "COMPOSITION"
                    },
                    {
                        "_type": "OBJECT_REF",
                        "id": {
                            "_type": "OBJECT_VERSION_ID",
                            "value": "abcdefgh-1323-42bc-b7f8-787f3660a0ba::91215053-854b-45b8-bb2a-3b0d255858d1::1"
                        },
                        "namespace": "local",
                        "type": "FOLDER"
                    }
                ],
                "audit": {
                    "system_id": "9624982A-9F42-41A5-9318-AE13D5F5031F",
                    "committer": {
                        "_type": "PARTY_IDENTIFIED",
                        "name": "bna"
                    },
                    "time_committed": {
                        "value": "2017-08-15T10:37:15.422+02:00"
                    },
                    "change_type": {
                        "value": "creation",
                        "defining_code": {
                            "terminology_id": {
                                "value": "openehr"
                            },
                            "code_string": "249"
                        }
                    },
                    "description": {
                        "value": "comment"
                    }
                }
            }

+ Response 400 

    `400 Bad Request` is returned when the are validation errors in one of the attached locatables, 
    modification type doesn't match the operation - i.e. first version
    of a composition with MODIFICATION.

    + Body 

            {
                "message": "Error message", 
                "validationErrors":[
                        "error1", "...", "errorN"
                ]
            }


+ Response 404

    `404 Not Found` is returned when an EHR with `ehr_id` does not exist.

    + Body 


### Get contribution by id [GET /ehr/{ehr_id}/contribution/{contribution_uid}]

+ Parameters

    + ehr_id: `7d44b88c-4199-4bad-97dc-d78268e01398` (string) - EHR identifier 
        taken from EHR.ehr_id.value
    + contribution_uid: `0826851c-c4c2-4d61-92b9-410fb8275ff0` (string) - CONTRIBUTION uid

+ Response 200 (application/json) 
    
    `200 OK` is returned when the CONTRIBUTION is successfully retrieved.

    + Body

            {
                "_type": "CONTRIBUTION",
                "uid": {
                    "value": "0826851c-c4c2-4d61-92b9-410fb8275ff0"
                },
                "versions": [
                    {
                        "_type": "OBJECT_REF",
                        "id": {
                            "_type": "OBJECT_VERSION_ID",
                            "value": "fb458d9c-1323-42bc-b7f8-787f3660a0b5::91215053-854b-45b8-bb2a-3b0d255858d1::1"
                        },
                        "namespace": "local",
                        "type": "COMPOSITION"
                    },
                     {
                        "_type": "OBJECT_REF",
                        "id": {
                            "_type": "OBJECT_VERSION_ID",
                            "value": "abcdefgh-1323-42bc-b7f8-787f3660a0ba::91215053-854b-45b8-bb2a-3b0d255858d1::1"
                        },
                        "namespace": "local",
                        "type": "FOLDER"
                    }
                ],
                "audit": {
                    "system_id": "9624982A-9F42-41A5-9318-AE13D5F5031F",
                    "committer": {
                        "_type": "PARTY_IDENTIFIED",
                        "name": "bna"
                    },
                    "time_committed": {
                        "value": "2017-08-15T10:37:15.422+02:00"
                    },
                    "change_type": {
                        "value": "creation",
                        "defining_code": {
                            "terminology_id": {
                                "value": "openehr"
                            },
                            "code_string": "249"
                        }
                    },
                    "description": {
                        "value": null
                    }
                }
            }

+ Response 404 

    `404 Not Found` is returned when an EHR with `ehr_id` does not exist or
    when a CONTRIBUTION with `contribution_uid` does not exist.

    + Body 


