## Directory [/ehr/{ehr_id}/directory]

Management of the [directory](https://specifications.openehr.org/releases/RM/latest/ehr.html#_directory)
[FOLDER](https://specifications.openehr.org/releases/RM/latest/common.html#_folder_class) resource.


### Create directory [POST /ehr/{ehr_id}/directory]

Creates a new directory FOLDER associated with the EHR identified by `ehr_id`.

+ Parameters

    + `ehr_id` (string) - EHR identifier taken from EHR.ehr_id.value

+ Request (application/json)

    + Body

            {
                "items": [...],
                "folders": [{}]
            }

    + Headers

            Prefer: return={representation|minimal}

+ Response 201 (application/json)

    New directory was created. Content body is only returned when
    `Prefer` header has `return=representation` otherwise only headers are
    returned.

    + Headers

            Location: {baseUrl}/ehr/{ehr_id}/directory/{version_uid}
            ETag: {version_uid}

    + Body

            {
                "uid": "...",
                "items": [...],
                "folders": [{}]
            }

+ Response 400

    Bad request - error creating a directory.

    + Body

+ Response 404

    No EHR with the given id.

    + Body


### Update directory [PUT /ehr/{ehr_id}/directory]

Updates directory FOLDER associated with the EHR identified by `ehr_id`.
The existing latest `version_uid` of directory FOLDER resource (i.e the `preceding_version_uid`) must be specified in the `If-Match` header.

+ Parameters

    + `ehr_id` (string) - EHR identifier taken from EHR.ehr_id.value

+ Request (application/json)

    + Header

            If-Match: {preceding_version_uid}
            Prefer: return={representation|minimal}

    + Body

            {
                "items": [...],
                "folders": [{}]
            }

+ Response 200 (application/json)

    Directory was updated.

    + Headers

            Location: {baseUrl}/ehr/{ehr_id}/directory/{version_uid}
            ETag: {version_uid}

    + Body

            {
                "uid": "...",
                "items": [...],
                "folders": [{}]
            }

+ Response 204

    Directory was updated.
    Returned when `Prefer` header is NOT set to `return=representation`.

    + Headers

            Location: {baseUrl}/ehr/{ehr_id}/directory/{version_uid}
            ETag: {version_uid}

+ Response 400

    Bad request - error when updating a directory.

    + Body

+ Response 404

    No EHR with the given id.

    + Body

+ Response 412

    `412 Precondition Failed` is returned when `If-Match` request header doesn't match the latest version on the service side.
    Returns also latest `version_uid` in the `Location` and `ETag` headers.

    + Headers

            Location: {baseUrl}/ehr/{ehr_id}/directory/{version_uid}
            ETag: {version_uid}

    + Body


### Delete directory [DELETE /ehr/{ehr_id}/directory]

Deletes directory FOLDER associated with the EHR identified by `ehr_id`.
The existing latest `version_uid` of directory FOLDER resource (i.e the `preceding_version_uid`) must be specified in the `If-Match` header.

+ Parameters

    + `ehr_id` (string) - EHR identifier taken from EHR.ehr_id.value

+ Request

    + Headers

            If-Match: {preceding_version_uid}

+ Response 204

    Directory was deleted.

    + Body

+ Response 400

    Bad request - error deleting directory.

    + Body

+ Response 404

    No EHR with the given id.

    + Body

+ Response 412

    `412 Precondition Failed` is returned when `If-Match` request header doesn't match the latest version on the service side.
    Returns also latest `version_uid` in the `Location` and `ETag` headers.

    + Headers

            Location: {baseUrl}/ehr/{ehr_id}/directory/{version_uid}
            ETag: {version_uid}

    + Body


### Get folder in directory version [GET /ehr/{ehr_id}/directory/{version_uid}{?path}]

Retrieves a FOLDER in a particular version of the directory identified by `version_uid` and associated with the EHR identified by `ehr_id`.

+ Parameters

    + `ehr_id` (string) - EHR identifier taken from EHR.ehr_id.value
    + version_uid (string) - version UID
    + path (string, optional) - path to a sub-folder

+ Response 200 (application/json)

    + Body

            {
                "uid": "...",
                "items": [...],
                "folders": [{}]
            }

+ Response 204

    No Folder at provided path.

    + Body

+ Response 404

    No EHR with the given id or no directory with specified version_uid.

    + Body


### Get folder in directory version at time [GET /ehr/{ehr_id}/directory{?version_at_time,path}]

Retrieves the version of the directory FOLDER associated with the EHR identified by `ehr_id`.
If `version_at_time` is supplied, retrieves the version extant at specified time, otherwise retrieves the latest directory FOLDER version.

+ Parameters

    + `ehr_id` (string) - EHR identifier taken from EHR.ehr_id.value
    + `version_at_time` (string, optional) - A timestamp in the extended ISO8601 format
    + path (string, optional) - path to a sub-folder

+ Response 200 (application/json)

    + Headers

            Location: {baseUrl}/ehr/{ehr_id}/directory/{version_uid}
            ETag: {version_uid}

    + Body

            {
                "uid": "...",
                "items": [...],
                "folders": [{}]
            }

+ Response 204

    EHR has no directory at `version_at_time` time or no Folder at provided path.

    + Body

+ Response 404

    No EHR with the given id.

    + Body

