## ADL 1.4 TEMPLATE [/definition/template/adl1.4]

Management of [AOM and ADL 1.4](https://specifications.openehr.org/releases/AM/latest) Operational Templates (OPTs). 
These templates can be created using [modelling tools](https://www.openehr.org/downloads/modellingtools) such as the Template Designer and the Archetype Designer.

Operational templates simplify the creation of openEHR-based input or storage implementations by, for a specific COMPOSITION template (use case), collecting all labels, requirements and constraints from all contained archetypes and sub-templates into a single easily parsed file. This file can be a basis for UI-generation/creation and for data validation.

Note that `GET /definition/template/adl1.4/{template_id}` can return both the original (canonical) `XML` based OPT format (if called with the `Accept: application/xml` request header) as well as a simplified `JSON`-based “web template” format (if called with the `Accept: application/openehr.wt+json` request header). For more details see the [data representation specification](overview.html#design-considerations-data-representation). 

<br/>


### Upload a template [POST /definition/template/adl1.4]

Upload a new ADL 1.4 operational template (OPT).

+ Request (application/xml)

    + Headers
    
            Prefer: return={representation|minimal}
            
    + Body

<!-- include(../examples/opt_template_adl14_01.xml) -->

+ Response 201 (application/xml)

    `201 Created` is returned when the template has been successfully uploaded.
    Server assigned `template_id` SHOULD be returned as part of the `Location` response header.
    An `ETag` response header MAY be present and contain the unique identifier of the operational template instance.
    Depending on the header `Prefer` either an empty body or a full representation body is returned.  

    + Headers

            Location: {baseUrl}/definition/template/adl1.4/Vital Signs
            ETag: "b4d7f203-b329-4e89-a58a-c605b19e94de"

    + Body

<!-- include(../examples/opt_template_adl14_01.xml) -->

+ Response 400

    `400 Bad Request` is returned when unable to upload a template, because of invalid content.

    + Body


+ Response 409

    `409 Conflict` is returned when a template with same `template_id` already exists.

    + Body


### List templates [GET /definition/template/adl1.4]

List the available ADL 1.4 operational templates (OPT) on the system.

+ Response 200 (application/json)

    `200 OK` is returned when the template list is successfully retrieved.
    
    + Body

            [
                {
                    "template_id": "Vital Signs",
                    "concept": "Vital Signs",
                    "archetype_id": "openEHR-EHR-COMPOSITION.encounter.v1",
                    "created_timestamp": "2017-08-14T19:24:56.639Z"
                }
            ]


### Get template [GET /definition/template/adl1.4/{template_id}]

Retrieves the ADL 1.4 operational template (OPT) identified by `template_id` identifier.

+ Parameters

    + template_id: `Vital Signs` (string) - template identifier

+ Request XML OPT1.4

    + Headers

            Accept: application/xml
    
+ Response 200 (application/xml)

    `200 OK` is returned when the template is successfully retrieved.

    + Body

<!-- include(../examples/opt_template_adl14_01.xml) -->

+ Response 400
    
    `400 Bad Request` is returned when the request has invalid `template_id` (i.e. an incorrectly formatted `template_id`).

    + Body    

+ Response 404

    `404 Not Found` is returned when a template with the specified `template_id` does not exist.

    + Body

+ Request as Web Template

    + Headers

            Accept: application/openehr.wt+json

+ Response 200 (application/openehr.wt+json)

    `200 OK` is returned when the template is successfully retrieved as Web Template format.

    + Body

<!-- include(../examples/web_template_01.json) -->

+ Response 400
    
    `400 Bad Request` is returned when the request has invalid `template_id` (i.e. an incorrectly formatted `template_id`).

    + Body    

+ Response 404

    `404 Not Found` is returned when a template with the specified `template_id` does not exist.

    + Body

+ Response 406
    
    `406 Not Acceptable` is returned when the service cannot produce a response matching `Accept` request header, i.e. the Web Template format is not supported.

    + Body


## ADL 2 TEMPLATE [/definition/template/adl2]

Management of [AOM2](https://specifications.openehr.org/releases/AM/latest/AOM2.html#_templates) templates. 
See also [ADL2 Template specifications](https://specifications.openehr.org/releases/AM/latest/ADL2.html#_templates).


### Upload a template [POST /definition/template/adl2/{?version}]

Upload a new ADL2 template.

+ Parameters

    + version: `1.0.1` (string, optional) - a SEMVER version format

+ Request (text/plain)

    + Headers
    
            Prefer: return={representation|minimal}
            
    + Body

            template (adl_version=2.0.5; rm_release=1.0.2)
                openEHR-EHR-COMPOSITION.test.v1.0.0
            
            specialize
                openEHR-EHR-COMPOSITION.discharge.v1
            
            language
                original_language = <[ISO_639-1::en]>
            
            description
                lifecycle_state = <"unmanaged">
                original_author = <
                    ["name"] = <"Ian McNicoll">
                    ["organisation"] = <"openEHR Foundation">
                    ["email"] = <"ian.mcnicoll@openehr.org">
            ...


+ Response 201 (text/plain)

    `201 Created` is returned when the template has been successfully uploaded. 
    Depending on the header `Prefer` either an empty body or a full representation body is returned.  
    The `version` in the `Location` header is optional.
    An `ETag` response header MAY be present and contain the unique identifier of the template instance.

    + Headers

            Location: {baseUrl}/definition/template/adl2/openEHR-EHR-COMPOSITION.test.v1.0.0/1.0.1
            ETag: "d8d643db-1cee-48ce-b609-12053077758f"

    + Body

            template (adl_version=2.0.5; rm_release=1.0.2)
                openEHR-EHR-COMPOSITION.test.v1.0.0
            
            specialize
                openEHR-EHR-COMPOSITION.discharge.v1
            
            language
                original_language = <[ISO_639-1::en]>
            
            description
                lifecycle_state = <"unmanaged">
                original_author = <
                    ["name"] = <"Ian McNicoll">
                    ["organisation"] = <"openEHR Foundation">
                    ["email"] = <"ian.mcnicoll@openehr.org">
            ...

+ Response 400

    `400 Bad Request` is returned when unable to upload a template, because of invalid content.

    + Body


+ Response 409

    `409 Conflict` is returned when a template with given `template_id` and `version` already exists.

    + Body


### List templates [GET /definition/template/adl2]

List the available ADL2 templates on the system.

+ Response 200 (application/json)

    `200 OK` is returned when the template list is successfully retrieved.
    
    + Body

            [
                {
                    "template_id": "openEHR-EHR-COMPOSITION.test.v1.0.0",
                    "version": "1.0.1", 
                    "concept": "Test",
                    "archetype_id": "openEHR-EHR-COMPOSITION.discharge.v1",
                    "created_timestamp": "2017-08-14T19:24:56.639Z"
                }
            ]


### Get template [GET /definition/template/adl2/{template_id}/{version_pattern}]

Retrieves the ADL2 template identified by `template_id` identifier.

If `version_pattern` is specified then the latest template version with given prefix pattern is returned. 
If `version_pattern` is omitted, then the latest version of the operational template is returned.

+ Parameters

    + template_id: `openEHR-EHR-COMPOSITION.test.v1.0.0` (string) - template identifier
    + version_pattern: `1.0` (string, optional) - SEMVER version pattern; this can be a complete version (i.e. 1.7.1) or partial prefix (i.e. 1.0)

+ Response 200 (text/plain)

    `200 OK` is returned when the template is successfully retrieved.

    + Body

            template (adl_version=2.0.5; rm_release=1.0.2)
                openEHR-EHR-COMPOSITION.test.v1.0.0
            
            specialize
                openEHR-EHR-COMPOSITION.discharge.v1
            
            language
                original_language = <[ISO_639-1::en]>
            
            description
                lifecycle_state = <"unmanaged">
                original_author = <
                    ["name"] = <"Ian McNicoll">
                    ["organisation"] = <"openEHR Foundation">
                    ["email"] = <"ian.mcnicoll@openehr.org">
            ...

+ Response 400
    
    `400 Bad Request` is returned when the request has invalid `template_id` (i.e. an incorrectly formatted `template_id`).

    + Body    

+ Response 404

    `404 Not Found` is returned when a template with the specified `template_id` and `version_pattern` does not exist.

    + Body
