FORMAT: 1A
HOST: http://www.openehr.org/api


<!-- include(overview.apib) -->

# Group COMPOSITION

## COMPOSITION [/ehrs/{ehrId}/compositions]

### Create a new composition [POST /ehrs/{ehrId}/compositions]

+ Parameters

    + ehrId (string) - EHR id

+ Request

    + Body (application/json)

            {
                "_type": "COMPOSITION",
                "name": {
                    "_type": "DV_TEXT",
                    "value": "Vital Signs"
                },
                ...
            }

    + Headers

            Prefer: return={representation/minimal}

+ Response 201

    New composition was created. Content body is only returned when
    `Prefer` header has `return=representation` otherwise only headers are
    returned.

    + Headers

            Location: /ehrs/{ehrId}/compositions/{versionUid}
            ETag: {versionUid}

    + Body

            {
                "$type": "COMPOSITION",
                "name": {
                    "_type": "DV_TEXT",
                    "value": "Vital Signs"
                },
                ...
            }

+ Response 400

    Bad request: either body of the request could not be read (or converted to a COMPOSITION object) or there were composition validation errors.

    + Body

            {
                "message": "Error message",
                "validationErrors": [
                    "error1", "error2"
                ]
            }

+ Response 404

    No EHR with the given id.

    + Body

### Update a composition [PUT /ehrs/{ehrId}/compositions/{objectId}]

+ Parameters

    + ehrId (string) - EHR id
    + objectId (string) - object id of the composition to update. This can be an exact versionUid or versionedObjectUid.
    In case of versionUid it has to be the last version.
    In case of versionedObjectUid, a `Match-If` may be supplied with the last versionUid which must match before update can succeed.

+ Request

    + Body (application/json)

            {
                "_type": "COMPOSITION",
                "name": {
                    "_type": "DV_TEXT",
                    "value": "Vital Signs"
                },
                ...
            }

    + Headers

            Match-If: {precedingVersionUid}
            Prefer: return={representation/minimal}

+ Response 200 (application/json)

    Returned when `Prefer` header is set to `return=representation`.

    + Headers

            Content-Location: /ehrs/{ehrId}/compositions/{versionUid}
            ETag: {versionUid}

    + Body

            {
                "_type": "COMPOSITION",
                "name": {
                    "_type": "DV_TEXT",
                    "value": "Vital Signs"
                },
                ...
            }

+ Response 204

    Returned when `Prefer` header is missing or NOT set to `return=representation`.

    + Headers

            Content-Location: /ehrs/{ehrId}/compositions/{versionUid}
            ETag: {versionUid}

+ Response 400 (application/json)

    Bad request: either body of the request could not be read (or converted to a COMPOSITION object) or there were composition validation errors.

    + Body

            {
                "message": "Error message",
                "validationErrors": [
                    "error1", "error2"
                ]
            }

+ Response 404

    No EHR with the supplied EHR id or no composition with the supplied object id.

    + Body

+ Response 412

    Returned when:
    - supplied objectId is versionedObjectUid and `Match-If` header doesn't match the last version
    - supplied objectId is versionUid and it's not the last version

    Returns last version in the `Content-Location` and `ETag` headers.

    + Headers

            Content-Location: /ehrs/{ehrId}/compositions/{versionUid}
            ETag: {versionUid}

    + Body

### Delete a composition [DELETE /ehrs/{ehrId}/compositions/{objectId}]

+ Parameters

    + ehrId (string) - EHR id
    + objectId (string) - object id of the composition to delete. This can be an exact versionUid or versionedObjectUid.
    In case of versionUid it has to be the last version.
    In case of versionedObjectUid, a `Match-If` may be supplied with the last versionUid which must match before update can succeed.

+ Request

    + Headers

            Match-If: {precedingVersionUid}

+ Response 204

    Composition was deleted.

    + Headers

            Content-Location: /ehrs/{ehrId}/compositions/{versionUid}
            ETag: {versionUid}

    + Body

+ Response 404

    No EHR with supplied EHR id or no composition with the given object id.

    + Body

+ Response 412

    Returned when:
    - supplied objectId is versionedObjectUid and `Match-If` header doesn't match the last version
    - supplied objectId is versionUid and it's not the last version

    Returns last version in the `Content-Location` and `ETag` headers.

    + Headers

            Content-Location: /ehrs/{ehrId}/compositions/{versionUid}
            ETag: {versionUid}

    + Body


### Get a composition by version uid [GET /ehrs/{ehrId}/compositions/{versionUid}]

+ Parameters

    + ehrId (string) - EHR id
    + versionUid (string) - version uid

+ Response 200 (application/json)

    + Body

            {
                "_type": "COMPOSITION",
                "name": {
                    "_type": "DV_TEXT",
                    "value": "Vital Signs"
                },
                ...
            }

+ Response 404

    No EHR with supplied EHR id or no composition with the supplied version uid.

    + Body

### Get a composition [GET /ehrs/{ehrId}/compositions/{versionedObjectUid}{?versionSelector}]

+ Parameters

    + ehrId (string) - EHR id
    + versionedObjectUid (string) - VERSIONED_COMPOSITION's uid
    + versionSelector (string, optional) - version time specifier

+ Response 200 (application/json)

    + Headers

            Content-Location: /ehrs/{ehrId}/compositions/{versionUid}
            ETag: {versionUid}

    + Body

            {
                "_type": "COMPOSITION",
                "name": {
                    "_type": "DV_TEXT",
                    "value": "Vital Signs"
                },
                ...
            }

+ Response 204 (application/json)

    No composition at specified versionSelector.

    + Body

+ Response 404

    No EHR with the supplied EHR id or no composition with the supplied versionedObjectUid.

    + Body

## VERSIONED_COMPOSITION [/ehrs/{ehrId}/versioned_compositions]

### Get a versioned composition [GET /ehrs/{ehrId}/versioned_compositions/{versionedObjectUid}]

Gets a complete VERSIONED_COMPOSITION.

+ Parameters

    + ehrId (string) - EHR id
    + versionedObjectUid (string) - VERSIONED_COMPOSITION's uid

+ Response 200 (application/json)

    + Headers

            Location: /ehrs/{ehrId}/versioned_compositions/{versionedObjectUid}

    + Body

            {
                "uid": "xxx",
                "owner_id": "{ehrId}",
                "time_created": "ISO8601 timestamp",
                "version_count: 12,
                "all_version_ids": [
                    "versioned_uid1",
                    "versioned_uid2",
                    ...
                ]
            }

+ Response 404

    No EHR with the supplied EHR id or no versioned composition with supplied versionedObjectUid.

    + Body


### Get a composition version by versionUid [GET /ehrs/{ehrId}/versioned_compositions/{versionedObjectUid}/versions/{versionUid}]

+ Parameters

    + ehrId (string) - EHR id
    + versionedObjectUid (string) - VERSIONED_COMPOSITION's uid
    + versionUid (string) - version uid

+ Response 200 (application/json)

    + Body

            {
                "contribution": {},
                "signature": "...",
                "commit_audit": {},
                "uid": "...",
                "data": {
                    "_type": "COMPOSITION",
                    "name": {
                        "_type": "DV_TEXT",
                        "value": "Vital Signs"
                    }
                    ...
                }
            }

+ Response 404

    No VERSIONED_COMPOSITION with uid or no version with versionUid.

    + Body

### Get a composition version [GET /ehrs/{ehrId}/versioned_compositions/{versionedObjectUid}/versions{?versionSelector}]

+ Parameters

    + ehrId (string) - EHR id
    + versionedObjectUid (string) - VERSIONED_COMPOSITION's uid
    + versionSelector (string, optional) - version time specifier

+ Response 200 (application/json)

    + Headers

            Location: /ehrs/{ehrId}/versioned_compositions/{versionedObjectUid}/versions/{versionUid}
            ETag: {versionUid}

    + Body

            {
                "contribution": {},
                "signature": "...",
                "commit_audit": {},
                "uid": "...",
                "data": {
                    "_type": "COMPOSITION",
                    "name": {
                        "_type": "DV_TEXT",
                        "value": "Vital Signs"
                    }
                    ...
                }
            }

+ Response 404

    No no VERSIONED_COMPOSITION with uid or no version with versionUid.

    + Body
