FORMAT: 1A
HOST: http://www.openehr.org/api/v1

# OpenEHR REST COMPOSITIONs API

`Release: `**`v1.0`**
`Status: `**`DEVELOPMENT`**

<!-- include(includes/overview.apib) -->

# Group COMPOSITION

<!-- include(includes/composition.apib) -->
