FORMAT: 1A
HOST: http://www.openehr.org/api 


<!-- include(overview.apib) -->

# Group CONTRIBUTION 

## CONTRIBUTION [/{ehrId}/contributions]

### Create a new contribution [POST /{ehrId}/contributions{?committerName}]

+ Parameters 

    + ehrId (string) - EHR id 
    + committerName (string) - Name of the committer

+ Request 

    + Body (application/json) 

            [
                {
                    "content": {/** openEHR locatable; composition or folder */},
                    "precedingVersionUid": "string",
                    "tags": [     {"key": "string", "value": "string"   } ], // vendor (DIPS) specific extension 
                    "versionLifecycleState": NUMBER // The version Lifecycle State (532=complete, 553=incomplete, 523=deleted)
                }
            ]

    + Headers

            Prefer: return={representation/minimal}

+ Response 201 

    New contribution was created. Content body is only returned when `Prefer` header has `return=representation` otherwise only headers are returned. 

    + Headers

            Location: /{ehrId}/contributions/{versionUid}
            ETag: {versionUid}

    + Body 

            [
                {
                    "content": {/** openEHR locatable; composition or folder */},
                    "precedingVersionUid": "string",
                    "tags": [     {"key": "string", "value": "string"   } ], // vendor (DIPS) specific extension 
                    "versionLifecycleState": 523
                }
            ]

+ Response 400 

    Bad request: validation errors in one of the attached locatables 

    + Body 

            {
                "message": "Error message", 
                "validationErrors":[
                        "error1", "...", "errorN"
                ]
            }


+ Response 401 

    Unauthorized.

    + Body 

+ Response 404 

    No EHR with the given id 

    + Body 

### Get a contribution by uid [GET /{ehrId}/contributions/{objectId}]

+ Parameters

    + ehrId (string) - EHR id 
    + objectId (string) - CONTRIBUTION's uid

+ Response 200 (application/json) 

    + Body

            {
                "_type": "CONTRIBUTION",
                "uid": {
                    "value": "0826851c-c4c2-4d61-92b9-410fb8275ff0"
                },
                "versions": [
                    {
                        "_type": "OBJECT_REF",
                        "id": {
                            "_type": "OBJECT_VERSION_ID",
                            "value": "fb458d9c-1323-42bc-b7f8-787f3660a0b5::91215053-854b-45b8-bb2a-3b0d255858d1::1"
                        },
                        "namespace": "local",
                        "type": "COMPOSITION"
                    },
                     {
                        "_type": "OBJECT_REF",
                        "id": {
                            "_type": "OBJECT_VERSION_ID",
                            "value": "abcdefgh-1323-42bc-b7f8-787f3660a0ba::91215053-854b-45b8-bb2a-3b0d255858d1::1"
                        },
                        "namespace": "local",
                        "type": "FOLDER"
                    }
                ],
                "audit": {
                    "system_id": "9624982A-9F42-41A5-9318-AE13D5F5031F",
                    "committer": {
                        "_type": "PARTY_IDENTIFIED",
                        "name": "bna"
                    },
                    "time_committed": {
                        "value": "2017-08-15T10:37:15+02:00"
                    },
                    "change_type": {
                        "value": "creation",
                        "defining_code": {
                            "terminology_id": {
                                "value": "openehr"
                            },
                            "code_string": "249"
                        }
                    },
                    "description": {
                        "value": null
                    }
                }
            }
+ Response 401

    Unauthorized

    + Body 

+ Response 403

    Forbidden 

    + Body 

+ Response 404 

    No contribution with the given id was found 

    + Body 

+ Response 500 

    Internal Server Error 

    + Body 
            