FORMAT: 1A
HOST: http://www.openehr.org/api/v1

# OpenEHR REST Models API

Release: **`v1.0`** <br>
Status: **`DEVELOPMENT`**

<!-- include(includes/overview.apib) -->

# Group Models 

This is a collection of resources to manage the clinical models of the openEHR Server. 
In basis we have a set of standard CRUD operations on archetype, templates and guides. 

<!-- include(includes/archetype.apib) --> 


<!-- include(includes/template.apib) -->


<!-- include(includes/aql.apib) -->


<!-- include(includes/gdl.apib) -->
