FORMAT: 1A
HOST: http://www.openehr.org/api/v1

# OpenEHR REST EHR API

Release: **_Release_**

Status: **`DEVELOPMENT`**

<!-- include(includes/overview.apib) -->

# Group EHR

<!-- include(includes/ehr.apib) -->

# Group EHR_STATUS

<!-- include(includes/ehr_status.apib) -->

# Group COMPOSITION

<!-- include(includes/composition.apib) -->

# Group DIRECTORY

<!-- include(includes/directory.apib) -->

# Group CONTRIBUTION

<!-- include(includes/contribution.apib) -->
