## GDL [/knowledge/gdl]

Management of GDL resources in the system. 

### List all available guides in the system [GET /knowledge/gdl]

+ Response 200 (application/json) 

    `200 OK` is returned when the resources are succesfully retrieved. 

    + Body

            [{
                    "guideId": "GuideOne.v1",
                    "validTo": "2016-05-26T12:04:43",
                    "createdTimeStamp": "2016-05-26T12:02:01",
                    "concept": "Guide one"
                },
                {
                    "guideId": "GuideTwo.v1",
                    "createdTimeStamp": "2016-05-26T12:04:43",
                    "concept": "Guide two"
                }
            ]

### Upload a new guide [POST /knowledge/gdl]

+ Request 
    
    + Body 

            {
              "gdl": "<the gdl as a UTF-8 string>"
            }

+ Response 201 (application/json) 

    `201 Created` is returned when the guide has been succesfully uploaded to the server. 

    + Headers

            Location: /knowledge/gdl/{guideId}


+ Response 400 

    `400 Bad Request` is returned when the server was unable to upload the guide. 

    + Body 

### Get a guide [GET /knowledge/gdls/{guideId}]  

+ Parameters
    
    + guideId (string) - the guideId 

+ Response 200 (application/json)
    `200 OK` is returned when the guide is succesfully retrieved. 

    + Body 

                "(GUIDE) <\n\tgdl_version = <..... "

+ Response 401 

    `401 Unauthorized` is returned when the request is not authorized. 

    + Body 