FORMAT: 1A
HOST: http://www.openehr.org/api/v1

# OpenEHR REST API

Following APIs are available:
 - [EHR](ehr.html)
 - [Query](simple_query.html)
 - [Definitions](definitions.html)
 - [CDS](cds.html)
