FORMAT: 1A
HOST: http://www.openehr.org/api/v1

# OpenEHR REST API

Release: **`0.9.1`**

Status: **`DEVELOPMENT`**

Following APIs are available:
 - [EHR](ehr.html)
 - [Query](query.html)
 - [Definitions](definitions.html)
