FORMAT: 1A
HOST: http://www.openehr.org/api/v1/knowledge 

<!-- include(overview.apib) -->

# Group Knowledge 

This is a collection of resources to manage the clinical knowledge of the openEHR Server. In basis we have a set of standard CRUD operations on archetype, templates and guides. 

<!-- include(archetype.apib) --> 


<!-- include(template.apib) -->


<!-- include(gdl.apib) -->