FORMAT: 1A
HOST: http://www.openehr.org/api/v1

# OpenEHR REST Query API

Release: **`v1.0`** <br>
Status: **`DEVELOPMENT`**

<!-- include(query_overview.apib) -->

# Group Query

<!-- include(includes/query.apib) -->