FORMAT: 1A
HOST: http://www.openehr.org/api/v1

# OpenEHR REST Query API

Release: **`0.9.1`**

Status: **`DEVELOPMENT`**

<!-- include(includes/query_overview.apib) -->

# Group Query
The REST API currently supports AQL queries. Other query types might be added at a later time. 

<!-- include(includes/query.apib) -->
