## TEMPLATE [/models/templates]

Management of OpenEHR operational templates. OpenEHR templates can be uploaded and downloaded as OPTs created
by modelling tools such as the Template Designer.

### Upload template [POST /models/templates]

Upload a new template.

+ Request

    + Body

            <template xmlns="http://schemas.openehr.org/v1">
                <language>
                    <terminology_id>
                        <value>ISO_639-1</value>
                    </terminology_id>
                    <code_string>en</code_string>
                </language>
                <description>
                    <original_author id="Original Author">Not Specified</original_author>
                    <lifecycle_state>Initial</lifecycle_state>
                    <other_details id="MetaDataSet:Sample Set ">Template metadata sample set </other_details>
            ...



+ Response 201 (application/json)

    `201 Created` is returned when the template has been successfully uploaded.

    + Headers

            Location: /models/templates/{template_id}

+ Response 400

    '400 Bad Request' is returned when unable to upload a template, because of invalid content.

    + Body


### List all templates [GET /models/templates]

List all available templates on the system

+ Response 200 (application/json)
    `200 OK` is returned when the EHR resource is successfully retrieved. 
    
    + Body

            [
                {
                    "template_id": "string",
                    "concept": "string",
                    "archetype_id": "string",
                    "valid_to": "2017-08-14T19:24:56.639Z",
                    "created_timeStamp": "2017-08-14T19:24:56.639Z"
                }
            ]


### Get template [GET /models/templates/{template_id}]

+ Parameters

    + template_id (string) - template id

+ Response 200 (application/json)
    `200 OK` is returned when the EHR resource is successfully retrieved.

    + Body

                    <template xmlns="http://schemas.openehr.org/v1">
                        <language>
                            <terminology_id>
                                <value>ISO_639-1</value>
                            </terminology_id>
                            <code_string>en</code_string>
                        </language>
                        <description>
                            <original_author id="Original Author">Not Specified</original_author>
                            <lifecycle_state>Initial</lifecycle_state>
                            <other_details id="MetaDataSet:Sample Set ">Template metadata sample set </other_details>
                    ...

+ Response 404

    `404 Not Found` is returned when a template with the specified id does not exist.

    + Body
