include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

This specification builds upon the Web Template serialization format that originated as part of the Better Platform EHR Server implementation by *Better d.o.o.* (formerly Marand, Slovenia).
The serialization format was further documented in the *EHRbase* implementation under the name "Simplified Data Template", which provided additional foundation for this specification.

=== Contributors

This specification has benefited from formal and informal input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following for their contributions.

* Thomas Beale, Ars Semantica (UK); openEHR Foundation Management Board.
* Christian Chevalley, Architect, EtherCIS, Thailand
* Borut Fabjan, Program Manager, Better, Slovenia
* Bostjan Lah, CTO, Better, Slovenia
* Ian McNicoll MD, FreshEHR, UK
* Bjørn Næss, DIPS, Norway
* Matija Polajnar, Tech Lead, Better, Slovenia
* Birger Haarbrandt, PhD, vitagroup, Germany
* Alex Vidrean, vitagroup, Germany
* Severin Kohler, Berlin Institute of Health (BIH) at Charite, Germany
* Sebastian Iancu, Architect, Code24, Netherlands

A significant part of the design ideas and content of this specification was adapted from:

* the EHRbase official documentation;
* the Marand 'Web Templates' specification, kindly provided by Better d.o.o.;
* the EtherCIS ECISFLAT format by the EtherCIS community;
* the XSD-based Template Data Schema (TDS) format developed by Ocean Health Systems.

=== Trademarks

* 'openEHR' is a registered trademark of the openEHR Foundation
== Conformance

When used with openEHR-REST API, the available calls to be conformance tested are the same as for other openEHR serialisation formats (canonical JSON etc), with a different representation format indicated by setting the appropriate `Content-Type` HTTP header.
Conformance of a data or software artefact to an openEHR specification is determined by a formal test of that artefact against the relevant openEHR Implementation Technology Specification(s) (ITSs).

:sectnums!:

include::partial$amendment_record.adoc[]
