//
// Archetyped.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Archetyped: Codable, JSONEncodable, Hashable {

    public var archetypeId: ArchetypeId
    public var templateId: TemplateId?
    public var rmVersion: String

    public init(archetypeId: ArchetypeId, templateId: TemplateId? = nil, rmVersion: String) {
        self.archetypeId = archetypeId
        self.templateId = templateId
        self.rmVersion = rmVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case archetypeId = "archetype_id"
        case templateId = "template_id"
        case rmVersion = "rm_version"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(archetypeId, forKey: .archetypeId)
        try container.encodeIfPresent(templateId, forKey: .templateId)
        try container.encode(rmVersion, forKey: .rmVersion)
    }
}

