//
// CareEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CareEntry: Codable, JSONEncodable, Hashable {

    public var _protocol: ItemStructure?
    public var guidelineId: ObjectRef?

    public init(_protocol: ItemStructure? = nil, guidelineId: ObjectRef? = nil) {
        self._protocol = _protocol
        self.guidelineId = guidelineId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _protocol = "protocol"
        case guidelineId = "guideline_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_protocol, forKey: ._protocol)
        try container.encodeIfPresent(guidelineId, forKey: .guidelineId)
    }
}

