//
// DvIntervalOfDateTime.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DvIntervalOfDateTime: Codable, JSONEncodable, Hashable {

    public var lower: DvDateTime?
    public var upper: DvDateTime?

    public init(lower: DvDateTime? = nil, upper: DvDateTime? = nil) {
        self.lower = lower
        self.upper = upper
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lower
        case upper
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(lower, forKey: .lower)
        try container.encodeIfPresent(upper, forKey: .upper)
    }
}

