//
// DvOrdered.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DvOrdered: Codable, JSONEncodable, Hashable {

    public var type: String? = "DV_ORDERED"
    public var normalStatus: CodePhrase?
    public var normalRange: DvInterval?
    public var otherReferenceRanges: [ReferenceRange]?

    public init(type: String? = "DV_ORDERED", normalStatus: CodePhrase? = nil, normalRange: DvInterval? = nil, otherReferenceRanges: [ReferenceRange]? = nil) {
        self.type = type
        self.normalStatus = normalStatus
        self.normalRange = normalRange
        self.otherReferenceRanges = otherReferenceRanges
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "_type"
        case normalStatus = "normal_status"
        case normalRange = "normal_range"
        case otherReferenceRanges = "other_reference_ranges"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(normalStatus, forKey: .normalStatus)
        try container.encodeIfPresent(normalRange, forKey: .normalRange)
        try container.encodeIfPresent(otherReferenceRanges, forKey: .otherReferenceRanges)
    }
}

