//
// DvParsable.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DvParsable: Codable, JSONEncodable, Hashable {

    public var value: String
    public var formalism: String

    public init(value: String, formalism: String) {
        self.value = value
        self.formalism = formalism
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case formalism
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(formalism, forKey: .formalism)
    }
}

