//
// DvProportion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DvProportion: Codable, JSONEncodable, Hashable {

    public var numerator: Double
    public var denominator: Double
    public var semanticType: Int
    public var precision: Int?

    public init(numerator: Double, denominator: Double, semanticType: Int, precision: Int? = nil) {
        self.numerator = numerator
        self.denominator = denominator
        self.semanticType = semanticType
        self.precision = precision
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numerator
        case denominator
        case semanticType = "semantic_type"
        case precision
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(numerator, forKey: .numerator)
        try container.encode(denominator, forKey: .denominator)
        try container.encode(semanticType, forKey: .semanticType)
        try container.encodeIfPresent(precision, forKey: .precision)
    }
}

