//
// DvQuantified.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DvQuantified: Codable, JSONEncodable, Hashable {

    public var magnitudeStatus: String? = "="

    public init(magnitudeStatus: String? = "=") {
        self.magnitudeStatus = magnitudeStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case magnitudeStatus = "magnitude_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(magnitudeStatus, forKey: .magnitudeStatus)
    }
}

