//
// EhrStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An EHR_STATUS resource */
public struct EhrStatus: Codable, JSONEncodable, Hashable {

    public var subject: PartyProxy
    public var isQueryable: Bool = true
    public var isModifiable: Bool = true
    public var otherDetails: ItemStructure?

    public init(subject: PartyProxy, isQueryable: Bool = true, isModifiable: Bool = true, otherDetails: ItemStructure? = nil) {
        self.subject = subject
        self.isQueryable = isQueryable
        self.isModifiable = isModifiable
        self.otherDetails = otherDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subject
        case isQueryable = "is_queryable"
        case isModifiable = "is_modifiable"
        case otherDetails = "other_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subject, forKey: .subject)
        try container.encode(isQueryable, forKey: .isQueryable)
        try container.encode(isModifiable, forKey: .isModifiable)
        try container.encodeIfPresent(otherDetails, forKey: .otherDetails)
    }
}

