//
// Element.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Element: Codable, JSONEncodable, Hashable {

    public var nullFlavour: DvCodedText?
    public var value: DataValue?
    public var nullReason: DvText?

    public init(nullFlavour: DvCodedText? = nil, value: DataValue? = nil, nullReason: DvText? = nil) {
        self.nullFlavour = nullFlavour
        self.value = value
        self.nullReason = nullReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nullFlavour = "null_flavour"
        case value
        case nullReason = "null_reason"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nullFlavour, forKey: .nullFlavour)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(nullReason, forKey: .nullReason)
    }
}

