//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Event: Codable, JSONEncodable, Hashable {

    public var time: DvDateTime
    public var state: ItemStructure?
    public var data: ItemStructure

    public init(time: DvDateTime, state: ItemStructure? = nil, data: ItemStructure) {
        self.time = time
        self.state = state
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case state
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(time, forKey: .time)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encode(data, forKey: .data)
    }
}

