//
// Folder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A FOLDER resource */
public struct Folder: Codable, JSONEncodable, Hashable {

    public var items: [ObjectRef]?
    public var folders: [Folder]?
    public var details: ItemStructure?

    public init(items: [ObjectRef]? = nil, folders: [Folder]? = nil, details: ItemStructure? = nil) {
        self.items = items
        self.folders = folders
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case items
        case folders
        case details
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(folders, forKey: .folders)
        try container.encodeIfPresent(details, forKey: .details)
    }
}

