//
// InstructionDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InstructionDetails: Codable, JSONEncodable, Hashable {

    public var type: String? = "INSTRUCTION_DETAILS"
    public var instructionId: LocatableRef
    public var activityId: String
    public var wfDetails: ItemStructure?

    public init(type: String? = "INSTRUCTION_DETAILS", instructionId: LocatableRef, activityId: String, wfDetails: ItemStructure? = nil) {
        self.type = type
        self.instructionId = instructionId
        self.activityId = activityId
        self.wfDetails = wfDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "_type"
        case instructionId = "instruction_id"
        case activityId = "activity_id"
        case wfDetails = "wf_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(instructionId, forKey: .instructionId)
        try container.encode(activityId, forKey: .activityId)
        try container.encodeIfPresent(wfDetails, forKey: .wfDetails)
    }
}

