//
// IsmTransition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IsmTransition: Codable, JSONEncodable, Hashable {

    public var type: String? = "ISM_TRANSITION"
    public var currentState: DvCodedText
    public var transition: DvCodedText?
    public var careflowStep: DvCodedText?
    public var reason: [DvText]?

    public init(type: String? = "ISM_TRANSITION", currentState: DvCodedText, transition: DvCodedText? = nil, careflowStep: DvCodedText? = nil, reason: [DvText]? = nil) {
        self.type = type
        self.currentState = currentState
        self.transition = transition
        self.careflowStep = careflowStep
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "_type"
        case currentState = "current_state"
        case transition
        case careflowStep = "careflow_step"
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(currentState, forKey: .currentState)
        try container.encodeIfPresent(transition, forKey: .transition)
        try container.encodeIfPresent(careflowStep, forKey: .careflowStep)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

