//
// Link.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Link: Codable, JSONEncodable, Hashable {

    public var meaning: DvText
    public var type: DvText
    public var target: DvEhrUri

    public init(meaning: DvText, type: DvText, target: DvEhrUri) {
        self.meaning = meaning
        self.type = type
        self.target = target
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meaning
        case type
        case target
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(meaning, forKey: .meaning)
        try container.encode(type, forKey: .type)
        try container.encode(target, forKey: .target)
    }
}

