//
// PartySelf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PartySelf: Codable, JSONEncodable, Hashable {

    public var type: String? = "PARTY_SELF"
    public var externalRef: PartyRef?

    public init(type: String? = "PARTY_SELF", externalRef: PartyRef? = nil) {
        self.type = type
        self.externalRef = externalRef
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "_type"
        case externalRef = "external_ref"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(externalRef, forKey: .externalRef)
    }
}

