//
// PartyRef.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Identifier for parties in a demographic or identity service. */
public struct PartyRef: Codable, JSONEncodable, Hashable {

    public var namespace: String
    public var type: String
    public var id: ObjectId

    public init(namespace: String, type: String, id: ObjectId) {
        self.namespace = namespace
        self.type = type
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case namespace
        case type
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(namespace, forKey: .namespace)
        try container.encode(type, forKey: .type)
        try container.encode(id, forKey: .id)
    }
}

