//
// PartyRelated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PartyRelated: Codable, JSONEncodable, Hashable {

    public var relationship: DvCodedText

    public init(relationship: DvCodedText) {
        self.relationship = relationship
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case relationship
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(relationship, forKey: .relationship)
    }
}

