//
// PartyIdentified.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PartyIdentified: Codable, JSONEncodable, Hashable {

    public var type: String? = "PARTY_IDENTIFIED"
    public var name: String?
    public var identifiers: [DvIdentifier]?
    public var externalRef: PartyRef?

    public init(type: String? = "PARTY_IDENTIFIED", name: String? = nil, identifiers: [DvIdentifier]? = nil, externalRef: PartyRef? = nil) {
        self.type = type
        self.name = name
        self.identifiers = identifiers
        self.externalRef = externalRef
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "_type"
        case name
        case identifiers
        case externalRef = "external_ref"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(identifiers, forKey: .identifiers)
        try container.encodeIfPresent(externalRef, forKey: .externalRef)
    }
}

