//
// ReferenceRange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReferenceRange: Codable, JSONEncodable, Hashable {

    public var meaning: DvText
    public var range: DvInterval

    public init(meaning: DvText, range: DvInterval) {
        self.meaning = meaning
        self.range = range
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meaning
        case range
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(meaning, forKey: .meaning)
        try container.encode(range, forKey: .range)
    }
}

