//
// TerminologyId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TerminologyId: Codable, JSONEncodable, Hashable {

    public var type: String? = "TERMINOLOGY_ID"
    public var value: String

    public init(type: String? = "TERMINOLOGY_ID", value: String) {
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "_type"
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(value, forKey: .value)
    }
}

