//
// VersionedObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VersionedObject: Codable, JSONEncodable, Hashable {

    public var type: String?
    public var uid: HierObjectId
    public var ownerId: ObjectRef
    public var timeCreated: DvDateTime

    public init(type: String? = nil, uid: HierObjectId, ownerId: ObjectRef, timeCreated: DvDateTime) {
        self.type = type
        self.uid = uid
        self.ownerId = ownerId
        self.timeCreated = timeCreated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type = "_type"
        case uid
        case ownerId = "owner_id"
        case timeCreated = "time_created"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(uid, forKey: .uid)
        try container.encode(ownerId, forKey: .ownerId)
        try container.encode(timeCreated, forKey: .timeCreated)
    }
}

