## ARCHETYPE [/definitions/archetypes]

Management of archetype resources. 

### List all archetypes [GET /definitions/archetypes]

List all available archetypes on the system

+ Response 200 (application/json) 

    `200 OK` is returned when the resources are successfully retrieved

    + Body

            [
                {
                    "archetype_id": "openEHR-EHR-EVALUATION.tobacco_smoking_summary.v0",
                    "description": "Summary or persisting information about tobacco use or consumption.",
                    "name": "Tobacco Use Summary",
                    "created_time": "2016-05-26T08:08:43"
                },
                {
                    "archetype_id": "openEHR-EHR-OBSERVATION.heart_rate.v1",
                    "description": "The characteristics of the heart rate and rhythm.",
                    "name": "Heart rate and rhythm",
                    "created_time": "2016-05-27T21:53:02"
                }
            ]
   

### Upload archetype [POST /definitions/archetypes]

Upload an archetype to the server 

+ Request 

    + Body 

            {
                "adl": "string"
            }

+ Response 201 (application/json)

    `201 Created` is returned when the archetype has been successfully uploaded to the server.

    + Headers

            Location: /definitions/archetypes/{archetype_id}

### Get archetype [GET /definitions/archetypes/{archetype_id}]

Get the archetype defined by the {archetype_id}

+ Parameters 
    + archetype_id (string) - archetype id

+ Response 200 (application/json) 
   
    `200 OK` is returned when the resources is successfully retrieved.

    + Body

            {
              /** JSON representation of an Archetype */
            }

