FORMAT: 1A
HOST: {baseUrl}/v1
API: cds
RELEASE: 1.x.0
STATUS: DEVELOPMENT

# CDS API

<!-- include(includes/copyright.html) -->

<h3>Amendment Record</h3>

| Issue | Details | Raiser, Implementer | Completed
|-------|---------|---------------------|-----------|
| 1.x.0 |  | 

# Group Clinical Decision Support 

<!-- include(includes/cds.apib) -->
