/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AbstractEntry
import org.openapitools.client.models.Action
import org.openapitools.client.models.AdminEntry
import org.openapitools.client.models.CareEntry
import org.openapitools.client.models.Evaluation
import org.openapitools.client.models.Instruction
import org.openapitools.client.models.ItemStructure
import org.openapitools.client.models.Observation

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 */


interface AdminEntry : AbstractEntry {

    @Json(name = "data")
    val `data`: ItemStructure
    @Json(name = "_type")
    val type: kotlin.String?
}

