/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuditDetails
import org.openapitools.client.models.DvCodedText
import org.openapitools.client.models.DvDateTime
import org.openapitools.client.models.DvEhrUri
import org.openapitools.client.models.DvMultimedia
import org.openapitools.client.models.DvText
import org.openapitools.client.models.PartyProxy

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param systemId 
 * @param timeCommitted 
 * @param changeType 
 * @param committer 
 * @param type 
 * @param description 
 */


interface Attestation : AuditDetails {

    @Json(name = "reason")
    val reason: DvText
    @Json(name = "is_pending")
    val isPending: kotlin.Boolean
    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "attested_view")
    val attestedView: DvMultimedia?
    @Json(name = "proof")
    val proof: kotlin.String?
    @Json(name = "items")
    val items: kotlin.collections.List<DvEhrUri>?
}

