/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AbstractEntry
import org.openapitools.client.models.ItemStructure
import org.openapitools.client.models.ObjectRef

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 */


interface CareEntry : AbstractEntry {

    @Json(name = "protocol")
    val protocol: ItemStructure?
    @Json(name = "guideline_id")
    val guidelineId: ObjectRef?
}

