/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CodePhrase
import org.openapitools.client.models.DvCodedText
import org.openapitools.client.models.DvText

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 */


interface DvCodedText : DvText {

    @Json(name = "defining_code")
    val definingCode: CodePhrase
    @Json(name = "_type")
    val type: kotlin.String?
}

