/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DataValue

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Type for representing identifiers of real-world entities. Typical identifiers include drivers licence number, social security number, veterans affairs number, prescription id, order id, and so on.  DV_IDENTIFIER is used to represent any identifier of a real thing, issued by some authority or agency. 
 *
 * @param type 
 */


interface DvIdentifier : DataValue {

    @Json(name = "id")
    val id: kotlin.String
    @Json(name = "issuer")
    val issuer: kotlin.String?
    @Json(name = "assigner")
    val assigner: kotlin.String?
    @Json(name = "type")
    val type: kotlin.String?
}

