/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DvCodedText
import org.openapitools.client.models.DvOrdered

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 */


interface DvOrdinal : DvOrdered {

    @Json(name = "symbol")
    val symbol: DvCodedText
    @Json(name = "value")
    val `value`: kotlin.Int
    @Json(name = "_type")
    val type: kotlin.String?
}

