/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DvAmount

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 */


interface DvProportion : DvAmount {

    @Json(name = "numerator")
    val numerator: java.math.BigDecimal
    @Json(name = "denominator")
    val denominator: java.math.BigDecimal
    @Json(name = "semantic_type")
    val semanticType: kotlin.Int
    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "precision")
    val precision: kotlin.Int?
}

