/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DvAmount
import org.openapitools.client.models.DvCount
import org.openapitools.client.models.DvDuration
import org.openapitools.client.models.DvProportion
import org.openapitools.client.models.DvQuantity

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 */


interface DvQuantity : DvAmount {

    @Json(name = "magnitude")
    val magnitude: java.math.BigDecimal
    @Json(name = "units")
    val units: kotlin.String
    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "precision")
    val precision: kotlin.Int?
    @Json(name = "units_system")
    val unitsSystem: kotlin.String?
    @Json(name = "units_display_name")
    val unitsDisplayName: kotlin.String?
}

