/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Composition
import org.openapitools.client.models.EhrStatus
import org.openapitools.client.models.ItemStructure
import org.openapitools.client.models.PartyProxy
import org.openapitools.client.models.Versionable

import com.squareup.moshi.Json

/**
 * An EHR_STATUS resource
 *
 * @param type 
 */


interface EhrStatus : Versionable {

    @Json(name = "subject")
    val subject: PartyProxy
    @Json(name = "is_queryable")
    val isQueryable: kotlin.Boolean
    @Json(name = "is_modifiable")
    val isModifiable: kotlin.Boolean
    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "other_details")
    val otherDetails: ItemStructure?
}

