/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Clstr
import org.openapitools.client.models.DataValue
import org.openapitools.client.models.DvCodedText
import org.openapitools.client.models.DvText
import org.openapitools.client.models.Element
import org.openapitools.client.models.Item

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 */


interface Element : Item {

    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "null_flavour")
    val nullFlavour: DvCodedText?
    @Json(name = "value")
    val `value`: DataValue?
    @Json(name = "null_reason")
    val nullReason: DvText?
}

