/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DvCodedText
import org.openapitools.client.models.DvDateTime
import org.openapitools.client.models.ItemStructure
import org.openapitools.client.models.Participation
import org.openapitools.client.models.PartyIdentified
import org.openapitools.client.models.Pathable

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 */


interface EventContext : Pathable {

    @Json(name = "start_time")
    val startTime: DvDateTime
    @Json(name = "setting")
    val setting: DvCodedText
    @Json(name = "end_time")
    val endTime: DvDateTime?
    @Json(name = "location")
    val location: kotlin.String?
    @Json(name = "other_context")
    val otherContext: ItemStructure?
    @Json(name = "health_care_facility")
    val healthCareFacility: PartyIdentified?
    @Json(name = "participations")
    val participations: kotlin.collections.List<Participation>?
}

