/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Activity
import org.openapitools.client.models.CareEntry
import org.openapitools.client.models.DvDateTime
import org.openapitools.client.models.DvParsable
import org.openapitools.client.models.DvText

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 */


interface Instruction : CareEntry {

    @Json(name = "narrative")
    val narrative: DvText
    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "expiry_time")
    val expiryTime: DvDateTime?
    @Json(name = "wf_definition")
    val wfDefinition: DvParsable?
    @Json(name = "activities")
    val activities: kotlin.collections.List<Activity>?
}

