/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ItemStructure
import org.openapitools.client.models.LocatableRef
import org.openapitools.client.models.Pathable

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 */


interface InstructionDetails : Pathable {

    @Json(name = "instruction_id")
    val instructionId: LocatableRef
    @Json(name = "activity_id")
    val activityId: kotlin.String
    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "wf_details")
    val wfDetails: ItemStructure?
}

