/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DvCodedText
import org.openapitools.client.models.DvText
import org.openapitools.client.models.Pathable

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 */


interface IsmTransition : Pathable {

    @Json(name = "current_state")
    val currentState: DvCodedText
    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "transition")
    val transition: DvCodedText?
    @Json(name = "careflow_step")
    val careflowStep: DvCodedText?
    @Json(name = "reason")
    val reason: kotlin.collections.List<DvText>?
}

