/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DataStructure
import org.openapitools.client.models.ItemList
import org.openapitools.client.models.ItemSingle
import org.openapitools.client.models.ItemTable
import org.openapitools.client.models.ItemTree

import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 */


interface ItemStructure : DataStructure {

    @Json(name = "_type")
    val type: kotlin.String?
}

