/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.DvEhrUri
import org.openapitools.client.models.DvText

import com.squareup.moshi.Json

/**
 * 
 *
 * @param meaning 
 * @param type 
 * @param target 
 */


data class Link (

    @Json(name = "meaning")
    val meaning: DvText,

    @Json(name = "type")
    val type: DvText,

    @Json(name = "target")
    val target: DvEhrUri

)

