/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuditDetails
import org.openapitools.client.models.ObjectVersionId

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A REVISION_HISTORY_ITEM resource
 *
 * @param versionId 
 * @param audits 
 */


data class RevisionHistoryItem (

    @Json(name = "version_id")
    val versionId: ObjectVersionId,

    @Json(name = "audits")
    val audits: kotlin.collections.List<AuditDetails>

)

