/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ArchetypeId
import org.openapitools.client.models.GenericId
import org.openapitools.client.models.HierObjectId
import org.openapitools.client.models.ObjectId
import org.openapitools.client.models.ObjectVersionId
import org.openapitools.client.models.TemplateId
import org.openapitools.client.models.TerminologyId

import com.squareup.moshi.Json

/**
 * 
 *
 * @param `value` 
 * @param type 
 */


interface TerminologyId : ObjectId {

    @Json(name = "_type")
    val type: kotlin.String?
}

