/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ObjectVersionId
import org.openapitools.client.models.TerminologyCode
import org.openapitools.client.models.UpdateAttestation
import org.openapitools.client.models.UpdateAudit
import org.openapitools.client.models.Versionable

import com.squareup.moshi.Json

/**
 * 
 *
 * @param lifecycleState 
 * @param `data` 
 * @param commitAudit 
 * @param precedingVersionUid 
 * @param signature 
 * @param attestations 
 */


data class UpdateVersion (

    @Json(name = "lifecycle_state")
    val lifecycleState: TerminologyCode,

    @Json(name = "data")
    val `data`: Versionable,

    @Json(name = "commit_audit")
    val commitAudit: UpdateAudit,

    @Json(name = "preceding_version_uid")
    val precedingVersionUid: ObjectVersionId? = null,

    @Json(name = "signature")
    val signature: kotlin.String? = null,

    @Json(name = "attestations")
    val attestations: kotlin.collections.List<UpdateAttestation>? = null

)

