/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AuditDetails
import org.openapitools.client.models.ImportedVersion
import org.openapitools.client.models.ObjectRef
import org.openapitools.client.models.OriginalVersion
import org.openapitools.client.models.Versionable

import com.squareup.moshi.Json

/**
 * A VERSION resource
 *
 * @param contribution 
 * @param commitAudit 
 * @param `data` 
 * @param type 
 * @param signature 
 */


interface Version {

    @Json(name = "contribution")
    val contribution: ObjectRef
    @Json(name = "commit_audit")
    val commitAudit: AuditDetails
    @Json(name = "data")
    val `data`: Versionable
    @Json(name = "_type")
    val type: kotlin.String?
    @Json(name = "signature")
    val signature: kotlin.String?
}

