/*
EHR API

Testing CONTRIBUTIONAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CONTRIBUTIONAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CONTRIBUTIONAPIService ContributionCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.CONTRIBUTIONAPI.ContributionCreate(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CONTRIBUTIONAPIService ContributionGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string
		var contributionUid string

		resp, httpRes, err := apiClient.CONTRIBUTIONAPI.ContributionGet(context.Background(), ehrId, contributionUid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
