/*
EHR API

Testing DIRECTORYAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_DIRECTORYAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DIRECTORYAPIService DirectoryCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.DIRECTORYAPI.DirectoryCreate(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DIRECTORYAPIService DirectoryDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		httpRes, err := apiClient.DIRECTORYAPI.DirectoryDelete(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DIRECTORYAPIService DirectoryGetAtTime", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.DIRECTORYAPI.DirectoryGetAtTime(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DIRECTORYAPIService DirectoryGetByVersionId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string
		var versionUid string

		resp, httpRes, err := apiClient.DIRECTORYAPI.DirectoryGetByVersionId(context.Background(), ehrId, versionUid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DIRECTORYAPIService DirectoryUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.DIRECTORYAPI.DirectoryUpdate(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
