/*
EHR API

Testing EHRSTATUSAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_EHRSTATUSAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EHRSTATUSAPIService EhrStatusGetAtTime", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.EHRSTATUSAPI.EhrStatusGetAtTime(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EHRSTATUSAPIService EhrStatusGetByVersionId", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string
		var versionUid string

		resp, httpRes, err := apiClient.EHRSTATUSAPI.EhrStatusGetByVersionId(context.Background(), ehrId, versionUid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EHRSTATUSAPIService EhrStatusUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.EHRSTATUSAPI.EhrStatusUpdate(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EHRSTATUSAPIService VersionedEhrStatusGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.EHRSTATUSAPI.VersionedEhrStatusGet(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EHRSTATUSAPIService VersionedEhrStatusRevisionHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.EHRSTATUSAPI.VersionedEhrStatusRevisionHistory(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EHRSTATUSAPIService VersionedEhrStatusVersionGetAtTime", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string

		resp, httpRes, err := apiClient.EHRSTATUSAPI.VersionedEhrStatusVersionGetAtTime(context.Background(), ehrId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EHRSTATUSAPIService VersionedEhrStatusVersionGetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ehrId string
		var versionUid string

		resp, httpRes, err := apiClient.EHRSTATUSAPI.VersionedEhrStatusVersionGetById(context.Background(), ehrId, versionUid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
