package org.openapitools.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.model.Attestation;
import org.openapitools.model.AuditDetails;
import org.openapitools.model.DvCodedText;
import org.openapitools.model.DvDateTime;
import org.openapitools.model.DvEhrUri;
import org.openapitools.model.DvMultimedia;
import org.openapitools.model.DvText;
import org.openapitools.model.PartyProxy;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * Attestation
 */

@JsonIgnoreProperties(
  value = "_type", // ignore manually set _type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the _type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Attestation.class, name = "ATTESTATION"),
  @JsonSubTypes.Type(value = AuditDetails.class, name = "ATTESTATION")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class Attestation extends AuditDetails {

  @JsonProperty("_type")
  private String type = "ATTESTATION";

  @JsonProperty("attested_view")
  private DvMultimedia attestedView;

  @JsonProperty("proof")
  private String proof;

  @JsonProperty("items")
  @Valid
  private List<DvEhrUri> items = null;

  @JsonProperty("reason")
  private DvText reason;

  @JsonProperty("is_pending")
  private Boolean isPending;

  public Attestation type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
  */
  
  @Schema(name = "_type", required = false)
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Attestation attestedView(DvMultimedia attestedView) {
    this.attestedView = attestedView;
    return this;
  }

  /**
   * Get attestedView
   * @return attestedView
  */
  @Valid 
  @Schema(name = "attested_view", required = false)
  public DvMultimedia getAttestedView() {
    return attestedView;
  }

  public void setAttestedView(DvMultimedia attestedView) {
    this.attestedView = attestedView;
  }

  public Attestation proof(String proof) {
    this.proof = proof;
    return this;
  }

  /**
   * Get proof
   * @return proof
  */
  
  @Schema(name = "proof", required = false)
  public String getProof() {
    return proof;
  }

  public void setProof(String proof) {
    this.proof = proof;
  }

  public Attestation items(List<DvEhrUri> items) {
    this.items = items;
    return this;
  }

  public Attestation addItemsItem(DvEhrUri itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
  */
  @Valid 
  @Schema(name = "items", required = false)
  public List<DvEhrUri> getItems() {
    return items;
  }

  public void setItems(List<DvEhrUri> items) {
    this.items = items;
  }

  public Attestation reason(DvText reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
  */
  @NotNull @Valid 
  @Schema(name = "reason", required = true)
  public DvText getReason() {
    return reason;
  }

  public void setReason(DvText reason) {
    this.reason = reason;
  }

  public Attestation isPending(Boolean isPending) {
    this.isPending = isPending;
    return this;
  }

  /**
   * Get isPending
   * @return isPending
  */
  @NotNull 
  @Schema(name = "is_pending", required = true)
  public Boolean getIsPending() {
    return isPending;
  }

  public void setIsPending(Boolean isPending) {
    this.isPending = isPending;
  }

  public Attestation systemId(String systemId) {
    super.setSystemId(systemId);
    return this;
  }

  public Attestation timeCommitted(DvDateTime timeCommitted) {
    super.setTimeCommitted(timeCommitted);
    return this;
  }

  public Attestation changeType(DvCodedText changeType) {
    super.setChangeType(changeType);
    return this;
  }

  public Attestation description(DvText description) {
    super.setDescription(description);
    return this;
  }

  public Attestation committer(PartyProxy committer) {
    super.setCommitter(committer);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attestation attestation = (Attestation) o;
    return Objects.equals(this.type, attestation.type) &&
        Objects.equals(this.attestedView, attestation.attestedView) &&
        Objects.equals(this.proof, attestation.proof) &&
        Objects.equals(this.items, attestation.items) &&
        Objects.equals(this.reason, attestation.reason) &&
        Objects.equals(this.isPending, attestation.isPending) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, attestedView, proof, items, reason, isPending, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Attestation {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attestedView: ").append(toIndentedString(attestedView)).append("\n");
    sb.append("    proof: ").append(toIndentedString(proof)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    isPending: ").append(toIndentedString(isPending)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

