package org.openapitools.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.openapitools.model.CodePhrase;
import org.openapitools.model.DvCodedText;
import org.openapitools.model.DvText;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * DvCodedText
 */

@JsonIgnoreProperties(
  value = "_type", // ignore manually set _type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the _type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = DvCodedText.class, name = "DV_CODED_TEXT"),
  @JsonSubTypes.Type(value = DvText.class, name = "DV_CODED_TEXT")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class DvCodedText extends DvText {

  @JsonProperty("_type")
  private String type = "DV_CODED_TEXT";

  @JsonProperty("defining_code")
  private CodePhrase definingCode;

  public DvCodedText type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
  */
  
  @Schema(name = "_type", required = false)
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DvCodedText definingCode(CodePhrase definingCode) {
    this.definingCode = definingCode;
    return this;
  }

  /**
   * Get definingCode
   * @return definingCode
  */
  @NotNull @Valid 
  @Schema(name = "defining_code", required = true)
  public CodePhrase getDefiningCode() {
    return definingCode;
  }

  public void setDefiningCode(CodePhrase definingCode) {
    this.definingCode = definingCode;
  }

  public DvCodedText value(String value) {
    super.setValue(value);
    return this;
  }

  public DvCodedText hyperlink(DvUri hyperlink) {
    super.setHyperlink(hyperlink);
    return this;
  }

  public DvCodedText language(CodePhrase language) {
    super.setLanguage(language);
    return this;
  }

  public DvCodedText encoding(CodePhrase encoding) {
    super.setEncoding(encoding);
    return this;
  }

  public DvCodedText formatting(String formatting) {
    super.setFormatting(formatting);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DvCodedText dvCodedText = (DvCodedText) o;
    return Objects.equals(this.type, dvCodedText.type) &&
        Objects.equals(this.definingCode, dvCodedText.definingCode) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, definingCode, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DvCodedText {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    definingCode: ").append(toIndentedString(definingCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

