package org.openapitools.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import org.openapitools.model.DvOrdered;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * DvQuantified
 */

@JsonIgnoreProperties(
  value = "_type", // ignore manually set _type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the _type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = DvAmount.class, name = "DV_QUANTIFIED"),
  @JsonSubTypes.Type(value = DvCount.class, name = "DV_QUANTIFIED"),
  @JsonSubTypes.Type(value = DvDate.class, name = "DV_QUANTIFIED"),
  @JsonSubTypes.Type(value = DvDateTime.class, name = "DV_QUANTIFIED"),
  @JsonSubTypes.Type(value = DvDuration.class, name = "DV_QUANTIFIED"),
  @JsonSubTypes.Type(value = DvProportion.class, name = "DV_QUANTIFIED"),
  @JsonSubTypes.Type(value = DvQuantity.class, name = "DV_QUANTIFIED"),
  @JsonSubTypes.Type(value = DvTemporal.class, name = "DV_QUANTIFIED"),
  @JsonSubTypes.Type(value = DvTime.class, name = "DV_QUANTIFIED")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class DvQuantified extends DvOrdered {

  private String type = "DV_QUANTIFIED";

  private String magnitudeStatus = "=";

  public DvQuantified type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
  */
  
  @Schema(name = "_type", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("_type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public DvQuantified magnitudeStatus(String magnitudeStatus) {
    this.magnitudeStatus = magnitudeStatus;
    return this;
  }

  /**
   * Get magnitudeStatus
   * @return magnitudeStatus
  */
  
  @Schema(name = "magnitude_status", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("magnitude_status")
  public String getMagnitudeStatus() {
    return magnitudeStatus;
  }

  public void setMagnitudeStatus(String magnitudeStatus) {
    this.magnitudeStatus = magnitudeStatus;
  }

  public DvQuantified normalStatus(CodePhrase normalStatus) {
    super.setNormalStatus(normalStatus);
    return this;
  }

  public DvQuantified normalRange(DvInterval normalRange) {
    super.setNormalRange(normalRange);
    return this;
  }

  public DvQuantified otherReferenceRanges(List<@Valid ReferenceRange> otherReferenceRanges) {
    super.setOtherReferenceRanges(otherReferenceRanges);
    return this;
  }

  public DvQuantified addOtherReferenceRangesItem(ReferenceRange otherReferenceRangesItem) {
    super.addOtherReferenceRangesItem(otherReferenceRangesItem);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DvQuantified dvQuantified = (DvQuantified) o;
    return Objects.equals(this.type, dvQuantified.type) &&
        Objects.equals(this.magnitudeStatus, dvQuantified.magnitudeStatus) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, magnitudeStatus, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DvQuantified {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    magnitudeStatus: ").append(toIndentedString(magnitudeStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

