package org.openapitools.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.model.Composition;
import org.openapitools.model.EhrStatus;
import org.openapitools.model.Folder;
import org.openapitools.model.ItemStructure;
import org.openapitools.model.Locatable;
import org.openapitools.model.ObjectRef;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * A FOLDER resource
 */

@Schema(name = "Folder", description = "A FOLDER resource")
@JsonIgnoreProperties(
  value = "_type", // ignore manually set _type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the _type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Composition.class, name = "FOLDER"),
  @JsonSubTypes.Type(value = EhrStatus.class, name = "FOLDER"),
  @JsonSubTypes.Type(value = Folder.class, name = "FOLDER")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class Folder extends Locatable {

  @JsonProperty("_type")
  private String type = "FOLDER";

  @JsonProperty("items")
  @Valid
  private List<ObjectRef> items = null;

  @JsonProperty("folders")
  @Valid
  private List<Folder> folders = null;

  @JsonProperty("details")
  private ItemStructure details;

  public Folder type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
  */
  
  @Schema(name = "_type", required = false)
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Folder items(List<ObjectRef> items) {
    this.items = items;
    return this;
  }

  public Folder addItemsItem(ObjectRef itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
  */
  @Valid 
  @Schema(name = "items", required = false)
  public List<ObjectRef> getItems() {
    return items;
  }

  public void setItems(List<ObjectRef> items) {
    this.items = items;
  }

  public Folder folders(List<Folder> folders) {
    this.folders = folders;
    return this;
  }

  public Folder addFoldersItem(Folder foldersItem) {
    if (this.folders == null) {
      this.folders = new ArrayList<>();
    }
    this.folders.add(foldersItem);
    return this;
  }

  /**
   * Get folders
   * @return folders
  */
  @Valid 
  @Schema(name = "folders", required = false)
  public List<Folder> getFolders() {
    return folders;
  }

  public void setFolders(List<Folder> folders) {
    this.folders = folders;
  }

  public Folder details(ItemStructure details) {
    this.details = details;
    return this;
  }

  /**
   * Get details
   * @return details
  */
  @Valid 
  @Schema(name = "details", required = false)
  public ItemStructure getDetails() {
    return details;
  }

  public void setDetails(ItemStructure details) {
    this.details = details;
  }

  public Folder name(DvText name) {
    super.setName(name);
    return this;
  }

  public Folder archetypeNodeId(String archetypeNodeId) {
    super.setArchetypeNodeId(archetypeNodeId);
    return this;
  }

  public Folder uid(UidBasedId uid) {
    super.setUid(uid);
    return this;
  }

  public Folder links(List<Link> links) {
    super.setLinks(links);
    return this;
  }

  public Folder addLinksItem(Link linksItem) {
    super.addLinksItem(linksItem);
    return this;
  }

  public Folder archetypeDetails(Archetyped archetypeDetails) {
    super.setArchetypeDetails(archetypeDetails);
    return this;
  }

  public Folder feederAudit(FeederAudit feederAudit) {
    super.setFeederAudit(feederAudit);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Folder folder = (Folder) o;
    return Objects.equals(this.type, folder.type) &&
        Objects.equals(this.items, folder.items) &&
        Objects.equals(this.folders, folder.folders) &&
        Objects.equals(this.details, folder.details) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, items, folders, details, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Folder {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    folders: ").append(toIndentedString(folders)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

