package org.openapitools.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.model.Archetyped;
import org.openapitools.model.DvText;
import org.openapitools.model.FeederAudit;
import org.openapitools.model.Link;
import org.openapitools.model.Pathable;
import org.openapitools.model.UidBasedId;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;

/**
 * Locatable
 */

@JsonIgnoreProperties(
  value = "_type", // ignore manually set _type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the _type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Action.class, name = "ACTION"),
  @JsonSubTypes.Type(value = Activity.class, name = "ACTIVITY"),
  @JsonSubTypes.Type(value = AdminEntry.class, name = "ADMIN_ENTRY"),
  @JsonSubTypes.Type(value = AbstractEntry.class, name = "AbstractEntry"),
  @JsonSubTypes.Type(value = Clstr.class, name = "CLUSTER"),
  @JsonSubTypes.Type(value = Composition.class, name = "COMPOSITION"),
  @JsonSubTypes.Type(value = CareEntry.class, name = "CareEntry"),
  @JsonSubTypes.Type(value = ContentItem.class, name = "ContentItem"),
  @JsonSubTypes.Type(value = DataStructure.class, name = "DATE_STRUCTURE"),
  @JsonSubTypes.Type(value = EhrStatus.class, name = "EHR_STATUS"),
  @JsonSubTypes.Type(value = Element.class, name = "ELEMENT"),
  @JsonSubTypes.Type(value = Evaluation.class, name = "EVALUATION"),
  @JsonSubTypes.Type(value = Event.class, name = "EVENT"),
  @JsonSubTypes.Type(value = Folder.class, name = "FOLDER"),
  @JsonSubTypes.Type(value = History.class, name = "HISTORY"),
  @JsonSubTypes.Type(value = Instruction.class, name = "INSTRUCTION"),
  @JsonSubTypes.Type(value = Item.class, name = "ITEM"),
  @JsonSubTypes.Type(value = ItemList.class, name = "ITEM_LIST"),
  @JsonSubTypes.Type(value = ItemSingle.class, name = "ITEM_SINGLE"),
  @JsonSubTypes.Type(value = ItemStructure.class, name = "ITEM_STRUCTURE"),
  @JsonSubTypes.Type(value = ItemTable.class, name = "ITEM_TABLE"),
  @JsonSubTypes.Type(value = ItemTree.class, name = "ITEM_TREE"),
  @JsonSubTypes.Type(value = Observation.class, name = "OBSERVATION"),
  @JsonSubTypes.Type(value = Versionable.class, name = "Versionable")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
public class Locatable extends Pathable {

  private DvText name;

  private String archetypeNodeId;

  private UidBasedId uid;

  @Valid
  private List<@Valid Link> links;

  private Archetyped archetypeDetails;

  private FeederAudit feederAudit;

  /**
   * Default constructor
   * @deprecated Use {@link Locatable#Locatable(DvText, String)}
   */
  @Deprecated
  public Locatable() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public Locatable(DvText name, String archetypeNodeId) {
    super();
    this.name = name;
    this.archetypeNodeId = archetypeNodeId;
  }

  public Locatable name(DvText name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
  */
  @NotNull @Valid 
  @Schema(name = "name", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("name")
  public DvText getName() {
    return name;
  }

  public void setName(DvText name) {
    this.name = name;
  }

  public Locatable archetypeNodeId(String archetypeNodeId) {
    this.archetypeNodeId = archetypeNodeId;
    return this;
  }

  /**
   * Get archetypeNodeId
   * @return archetypeNodeId
  */
  @NotNull 
  @Schema(name = "archetype_node_id", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("archetype_node_id")
  public String getArchetypeNodeId() {
    return archetypeNodeId;
  }

  public void setArchetypeNodeId(String archetypeNodeId) {
    this.archetypeNodeId = archetypeNodeId;
  }

  public Locatable uid(UidBasedId uid) {
    this.uid = uid;
    return this;
  }

  /**
   * Get uid
   * @return uid
  */
  @Valid 
  @Schema(name = "uid", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("uid")
  public UidBasedId getUid() {
    return uid;
  }

  public void setUid(UidBasedId uid) {
    this.uid = uid;
  }

  public Locatable links(List<@Valid Link> links) {
    this.links = links;
    return this;
  }

  public Locatable addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Get links
   * @return links
  */
  @Valid 
  @Schema(name = "links", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("links")
  public List<@Valid Link> getLinks() {
    return links;
  }

  public void setLinks(List<@Valid Link> links) {
    this.links = links;
  }

  public Locatable archetypeDetails(Archetyped archetypeDetails) {
    this.archetypeDetails = archetypeDetails;
    return this;
  }

  /**
   * Get archetypeDetails
   * @return archetypeDetails
  */
  @Valid 
  @Schema(name = "archetype_details", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("archetype_details")
  public Archetyped getArchetypeDetails() {
    return archetypeDetails;
  }

  public void setArchetypeDetails(Archetyped archetypeDetails) {
    this.archetypeDetails = archetypeDetails;
  }

  public Locatable feederAudit(FeederAudit feederAudit) {
    this.feederAudit = feederAudit;
    return this;
  }

  /**
   * Get feederAudit
   * @return feederAudit
  */
  @Valid 
  @Schema(name = "feeder_audit", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("feeder_audit")
  public FeederAudit getFeederAudit() {
    return feederAudit;
  }

  public void setFeederAudit(FeederAudit feederAudit) {
    this.feederAudit = feederAudit;
  }

  public Locatable type(String type) {
    super.setType(type);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Locatable locatable = (Locatable) o;
    return Objects.equals(this.name, locatable.name) &&
        Objects.equals(this.archetypeNodeId, locatable.archetypeNodeId) &&
        Objects.equals(this.uid, locatable.uid) &&
        Objects.equals(this.links, locatable.links) &&
        Objects.equals(this.archetypeDetails, locatable.archetypeDetails) &&
        Objects.equals(this.feederAudit, locatable.feederAudit) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, archetypeNodeId, uid, links, archetypeDetails, feederAudit, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Locatable {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    archetypeNodeId: ").append(toIndentedString(archetypeNodeId)).append("\n");
    sb.append("    uid: ").append(toIndentedString(uid)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    archetypeDetails: ").append(toIndentedString(archetypeDetails)).append("\n");
    sb.append("    feederAudit: ").append(toIndentedString(feederAudit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

