=== S_OBSERVATION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*S_OBSERVATION*

h|*Description*
2+a|Variant of `S_OBSERVATION` to use for single sample Observations.

h|*Inherit*
2+|`S_CARE_ENTRY`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*data*: `List<S_EVENT>`
a|Converted from `OBSERVATION._data.events[1]_`.

h|*0..1*
|*state*: `List<S_EVENT>`
a|Converted from `OBSERVATION._state.events[1]_`.

h|*0..1*
|*history_origin*: `String`
a|For multi-event series, converted from `OBSERVATION._data.origin_`.

TODO: should be called `_data_origin_`.

h|*0..1*
|*history_period*: `String`
a|For multi-event series, converted from `OBSERVATION._data.period_`.

TODO: should be called `_data_period_`.

h|*0..1*
|*history_summary*: `S_ITEM`
a|For multi-event series, converted from `OBSERVATION._data.summary_`.

TODO: should be called `_data_summary_`.

h|*0..1*
|*history_duration*: `String`
a|For multi-event series, converted from `OBSERVATION._data.duration_`.


TODO: should be called `_data_duration_`.

h|*0..1*
|*state_origin*: `String`
a|For multi-event series, converted from `OBSERVATION._state.origin_`.

h|*0..1*
|*state_period*: `String`
a|For multi-event series, converted from `OBSERVATION._state.period_`.

h|*0..1*
|*state_summary*: `S_ITEM`
a|For multi-event series, converted from `OBSERVATION._state.summary_`.

h|*0..1*
|*state_duration*: `String`
a|For multi-event series, converted from `OBSERVATION._state.duration_`.
|===
