= Service Discovery

A _CDR_ usually has multiple endpoints of interest. Some of these are the OAuth2's `.well-known` endpoints, like the Token and Authentication endpoints, while others are data resource or service endpoints defined by the openEHR REST APIs, FHIR APIs, DICOMWeb APIs, vendor's proprietary APIs to name a few.

The *SMART Service Discovery* builds on the FHIR {hl7_fhir}/smart-app-launch/conformance.html#using-well-known[`.well-known/smart-configuration`^] and enables a _CDR_ to advertise multiple <<_services,services>> alongside the OAuth2 `.well-known` endpoints for <<_authentication_endpoints,authentication>>.

Given a vendor's base URL of `\https://ehr.example.com`, the SMART configuration endpoint should be available at `\https://ehr.example.com/.well-known/smart-configuration`.

[NOTE]
====
The CDR vendor can choose to make `\https://ehr.example.com` the base URL of their FHIR endpoint if they want to maintain backward compatibility for _SMART on FHIR_ applications, since these apps assume that the base URL is always the FHIR server.
====

An example of a response from `/.well-known/smart-configuration` will look like this:

[source,json]
--------
{
  "issuer": "https://ehr.example.com",
  "jwks_uri": "https://ehr.example.com/.well-known/jwks.json",
  "authorization_endpoint": "https://ehr.example.com/auth/authorize",
  "token_endpoint": "https://ehr.example.com/auth/token",
  "services": {
    "org.openehr.rest" : {
      "baseUrl":"https://ehr.example.com/openehr/rest/v1",
      "description": "The openEHR official API baseUrl",
      "documentation": "https://example.com/openehr/docs",
      "openapi": "https://example.com/openehr/rest/v1/openapi.json"
    },
    "org.fhir.rest" : { 
      "baseUrl":"https://ehr.example.com/",
      "description": "The FHIR API baseUrl"
    },
    "com.amazon.aws.s3.rest": {
      "baseUrl":"https://s3.example.com/storage",
      "documentation": "https://example.com/s3/docs",
      "openapi": "https://example.com/s3/openapi.json"
    },
    "com.example.demographics": {
      "baseUrl":"https://demographics.example.com/rest"
    }
  },
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic",
    "private_key_jwt"
  ],
  "grant_types_supported": [
    "authorization_code",
    "client_credentials"
  ],
  "registration_endpoint": "https://ehr.example.com/auth/register",
  "scopes_supported": ["openid", "profile", "launch", "launch/patient", "patient/*.rs", "user/*.rs", "offline_access"],
  "response_types_supported": ["code"],
  "management_endpoint": "https://ehr.example.com/user/manage",
  "introspection_endpoint": "https://ehr.example.com/user/introspect",
  "revocation_endpoint": "https://ehr.example.com/user/revoke",
  "code_challenge_methods_supported": ["S256"],
  "capabilities": [
    "launch-ehr",
    "permission-patient",
    "permission-v2",
    "client-public",
    "client-confidential-symmetric",
    "context-ehr-patient",
    "sso-openid-connect",
    "launch-openehr-ehr",
    "openehr-permission-v1",
	"launch-base64-json"
  ]
}
--------

== Authentication endpoints

The following configurations keys should be exactly the same as in the OAuth2 + OIDC protocol's `.well-known/openid-configuration` as per https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect Discovery 1.0^] specifications:

- `isuer`
- `jwks_uri`
- `authorization_endpoint`
- `token_endpoint`
- `token_endpoint_auth_methods_supported`
- `grant_types_supported`
- `scopes_supported`
- `response_types_supported`
- `introspection_endpoint`
- `revocation_endpoint`
- `code_challenge_methods_supported`

== Services

A response from the SMART Configuration endpoint should include besides the {hl7_fhir}/smart-app-launch/conformance.html#metadata[FHIR metadata^] also a hash of all available `services` on the _CDR_. The `services` section allows the application to discover the APIs of all services that can be used along with a description and documentation. The section is represented as a hash, where the key is represented by a reverse domain name of the service (e.g. `org.openehr.rest`), and the value represents the service endpoints specification.

The service list should minimally include the openEHR REST APIs endpoints specification available on the _CDR_, using the key `org.openehr.rest`. For consistency reason, the list should also include the specification of the FHIR server using the key `org.fhir.rest`:

* `org.openehr.rest`: The base URL of the openEHR REST APIs `*(required)*`
* `org.fhir.rest`: The base URL of the FHIR APIs `*(recommended)*`

The CDR vendor may add additional services to the list, for example:

* `org.dicomstandard.dicomweb.rest`: The base URL of the DICOMWeb REST API
* `com.amazon.aws.s3.rest`: The base URL of an AWS S3 compatible REST API
* `com.example.demographics`: The base URL of a proprietary service that is not part of the openEHR, FHIR or DICOMWeb specifications

Each service specification should include the following configurations:

* `baseUrl`: The base URL of the service `*(required)*`
* `description`: A short description of the service
* `documentation`: A URL to the documentation of the service
* `openapi`: A URL to the OpenAPI specification of the service

As an example, the openEHR REST APIs endpoints may be described as:

[source,json]
--------
{
    "org.openehr.rest" : {
        "baseUrl":"https://ehr.example.com/openehr/rest/v1",
        "description": "The openEHR official API baseUrl",
        "documentation": "https://example.com/openehr/docs",
        "openapi": "https://example.com/openehr/rest/v1/openapi.json"
    }
}
--------

== Capabilities

The `capabilities` section is an array that should include all relevant SMART capabilities. Besides {hl7_fhir}/smart-app-launch/conformance.html#capabilities[FHIR capabilities^], the following additional values should be used in order to indicate the ability to launch an application using openEHR artefacts:

* `launch-openehr-ehr` - support to select an EHR context within openEHR returned as the `ehr` parameter in a token.
* `launch-openehr-episode` - support to launch and select an Episode context returned as the `episode` parameter in a token.
* `openehr-permission-v1` - support for the scope and authorization scheme described below for openEHR REST APIs
* `launch-base64-json` - support for the `launch` URL parameter being a base64 encoded JSON of the context.
