= Overview

== Background

*SMART* stands for “Substitutable Medical Applications and Reusable Technologies”, a healthcare standard through which applications can access clinical information through a data store. It was initially proposed by https://smarthealthit.org/[SMART Health IT^] project and was later specified as {hl7_fhir}/smart-app-launch/[SMART on FHIR^], a protocol which works on top of the {hl7_fhir}[FHIR APIs^] facilitating access to data. The specification builds on {ietf_html}/rfc6749[OAuth2^] and {oidc_authentication}[OpenID Connect (OIDC)^], which are industry standards for authentication and authorization, and allows 3rd-party applications to authorize and seamlessly work with any system that implements the protocol.

== Glossary

[width="100%",cols="1,7",options="header"]
|=======================================================================
|Term | Definition
|Vendor | An entity that provides software to end-users.
|User | This is the real person or software agent who is using the Application to perform some function. This is often referred to as the "end-user".
|Application | A software application developed by a vendor, designed to work with the Platform and/or Launcher built by the same or another vendor. This is also known as the "client" in terms of OAuth roles, and often referred to as the "SMART App" by _SMART on FHIR_ specification.
|Platform | A software system consisting at least of an Authorization Server, an openEHR Clinical Data Repository (CDR) and a FHIR Server, providing openEHR REST APIs, FHIR APIs and potentially other APIs. This is sometimes also known in the _SMART on FHIR_ specification as the "EHR system". The authentication and authorization server that provides APIs consistent with the OAuth2 framework specification and the SMART on openEHR protocol.
|Launcher | User-facing software, usually built by the Platform vendor, that serves to launch other Applications within a context of a Patient or Practitioner. The Launcher can be part of the Platform (i.e. a Portal) or a completely separate application.
|EHR | A (session) context that relates to an {openehr_rm_ehr}#_ehr_package[openEHR `EHR` container^] and the associated Patient, representing the subject on which the Application will work.
|=======================================================================

[NOTE]
====
The {hl7_fhir}/smart-app-launch/[SMART on FHIR^] specifications uses the term '_EHR_' and '_EHR system_' to refer to a software system comprising a FHIR Server, Authorization Server and potentially other components, including a _Launcher_.
On the other hand, openEHR has specification for an {openehr_rm_ehr}[EHR Information Model^], including a {openehr_rm_ehr}#_root_ehr_object[root `EHR` container^].

In order to avoid any confusion between the meaning of '_EHR_' in the context of SMART, this specification will only use this term in relation with openEHR concepts (i.e. EHR type, EHR ID, etc.), and will use substitutes for FHIR's '_EHR_' concept.
====

== Why SMART on openEHR?

A popular vision nowadays is considering that a single software vendor cannot provide all the necessary tools and software for a healthcare system while still maintaining a high level of quality and a low cost of ownership. Independent vendors who focus on a specific topic or problem to be solved may have an edge over monolithic "suites" of software that try to do everything.

In practice, this requires applications from multiple vendors working together to provide a complete solution, often named "best-of-breed" architecture. This is implemented currently by long tedious manual "integration" phase, where the multiple vendors collaborate to make their software work together - a very expensive process, often a major barrier to entry for new vendors.

The SMART specification aims to solve this problem by providing a standard way for systems and applications to work together, as it defines a contract between the _Application vendor_ and the _Platform vendor_. This contract covers the following requirements:

- The _Application_ should have the ability to be hosted on a domain owned by the _Application vendor_
- The _Platform_ should have the ability to be hosted on a domain owned by the _Platform vendor_
- The _Application_ needs a way to discover API services offered by the _Platform_
- The _Application_ needs a way to authenticate with the _Platform_ to access the APIs offered by the _Platform_
- The _Application_ needs a way to understand the "context" while they are open, by letting the _Platform_ handle EHR and Episode selection
- The _Application_ needs a way to embed within the _Platform_'s user interface while maintaining the "context" to provide a seamless user experience

The *SMART on openEHR* specification aims to maintain compatibility with {hl7_fhir}/smart-app-launch/[SMART on FHIR^] while making this protocol work also with {openehr_its_rest_releases}[openEHR REST APIs^] and potentially more other APIs. It is meant to describe a framework for the following aspects:

* <<_application_registration,Application Registration>>
* <<_service_discovery,Service Discovery>>
* <<_authentication_authorization_and_scopes,Authentication, Authorization and Scopes>>
* <<_context_selection,Context Selection>>
* <<_embedded_iframe_launch,Embedded iFrame Launch>>

== Requirements

The {openehr_rm}[openEHR Reference Model^] and openEHR REST APIs provide a foundation for interoperable _Applications_. For such applications to be truly portable between systems and vendors, there is a requirement for a uniform _authentication_ and _authorization_ process.

Many of such applications also function in the _context_ of a single EHR or Patient, and potentially of a single Episode. Selection of this _context_ also becomes essential before lunching the _Application_.
