= Overview

== Background

*SMART* stands for “Substitutable Medical Applications and Reusable Technologies”, a healthcare standard through which applications can access clinical information through a data store. It was initially proposed by https://smarthealthit.org/[SMART Health IT^] project and was later on specified as {hl7_fhir}/smart-app-launch/[SMART on FHIR^], a protocol which works on top of {hl7_fhir}[FHIR APIs^]. The specification builds on {ietf_html}/rfc6749[OAuth2^] and https://openid.net/specs/openid-connect-core-1_0.html#Authentication[OIDC Core^] which are industry standards for authentication and authorization, and allows 3rd party apps to seamlessly work with any (FHIR) EHR system that implements the protocol.

The *SMART on openEHR* specification aims to be backward compatible with _SMART on FHIR_ while making this protocol work for vendors utilizing also openEHR REST APIs and more.

== Glossary

[width="100%",cols="2,2",options="header"]
|=======================================================================
|Term | Definition
|Vendor | An entity that provides software to end-users.
|Application | Software developed by the vendor or an external entity designed to work with the CDR and/or Launcher built by the vendor.
|CDR | A system comprising of an openEHR Clinical Data Repository and a FHIR Server, providing openEHR and FHIR REST APIs.
|OAuth2 Server | An authentication server that provides APIs consistent with the OAuth2 specification and will be extended to the SMART protocol that will be described in this document
|Launcher | User facing software built by the CDR vendor that serves to launch other applications within a context of a patient or practitioner. This can be the main “EHR system” or a separate application.
|=======================================================================

== Why SMART on openEHR?

A popular vision nowadays is considering that a single software vendor cannot provide all the necessary tools and software for a healthcare system while still maintaining a high level of quality and a low cost of ownership. Independent vendors who focus on a specific topic or problem to be solved may have an edge over monolithic "suites" of software that try to do everything.

In practice, this requires applications from multiple vendors working together to provide a complete solution, often named "best-of-breed". This is currently done is by long, tedious manual "integration" phase where the vendors work together to make their software work together - a very expensive process and is a major barrier to entry for new vendors.

The SMART specification aims to solve this problem by providing a standard way for systems and applications to work together, as it defines a contract between the _Application vendor_ and the _CDR vendor_. This contract covers the following requirements:

- The _Application_ should have the ability to be hosted on a domain owned by the _Application vendor_
- The _CDR_ should have the ability to be hosted on a domain owned by the _CDR vendor_
- The _Application_ needs a way to discovery API services offered by the _CDR_
- The _Application_ needs a way to authenticate with the _CDR_ to access the APIs offered by the _CDR_
- The _Application_ needs a way to understand the "context" their app should open in by letting the _CDR_ handle EHR and Episode selection
- The _Application_ needs a way to embed within the _CDR_'s user interface while maintaining the "context" to provide a seamless user experience

The {openehr_rm}[openEHR Reference Model^] and {openehr_its_rest_releases}[openEHR REST APIs^] provide a foundation for interoperable applications. For applications to be truly portable between systems and vendors, there is a requirement for a uniform _authentication_ and _authorization_.
Many of such applications also function in the _context_ of a single EHR, and potentially of a single Episode. Selection of this _context_ also becomes essential before lunching.

The *SMART on openEHR* specification is meant to provide a framework for the following aspects:

* <<_application_registration,Application Registration>>
* <<_service_discovery,Service Discovery>>
* <<_authentication_authorization_and_scopes,Authentication and Authorization>>
* <<_context_selection,Context Selection>>
* <<_embedded_iframe_launch,Embedded iFrame Launch>>
