= Authentication, Authorization and Scopes

== Authentication
The application can authenticate with the CDR using standard {ietf_html}/rfc6749[OAuth2.0 protocol^].

The CDR SHOULD support at least the following basic flows:

- {ietf_html}/rfc6749#section-1.3.1[Authorization Code Flow^] with {ietf_html}/rfc7636[PKCE^]
- {ietf_html}/rfc6749#section-1.3.1[Authorization Code Flow^] with client secret
- {ietf_html}/rfc6749#section-1.3.4[Client Credentials Flow^]
- {ietf_html}/rfc7515[JWS Assertion Flow^] (RFC7515)

The supported flows SHOULD be advertised in the `.well-known/smart-configuration` endpoint.

The recommended authentication flow depends on the type of the application. Here we make a distinction between the different kinds of applications based on whether or not it can hold a client secret. The following types of applications are considered:

- **Confidential Clients**: Have the ability to hold a client secret. This includes web applications running on a server and backend applications.
- **Public Clients**: Do not have the ability to hold a client secret. This includes mobile applications and single page web applications.

The distinction can also be made on the basis of the user interaction. The following types of applications are considered:

- **Patient facing**: The patient is the direct user of this application, or is opened up by a practitioner within the context of a patient. Can also be opened within the context of an episode, but is optional.
- **Practitioner facing**: The practitioner is the direct user of this application. Can be opened up within the context of a patient, or episode, but is not mandatory.
- **Backend**: The application is not directly used by a user, but is used by other applications or services in the background.

It is recommended that Patient and Practitioner facing applications use one of the Authorization Code Flows to obtain necessary user information and context. Confidential clients can use the Authorization Code Flow with PKCE or the Authorization Code Flow with Client Secret. Public clients SHOULD always use the Authorization Code Flow with PKCE. Backend applications SHOULD always use confidential clients and use the JWS Assertion Flow or the Client Credentials Flow.

The following table shows the recommended flow for a few example application.

[width="100%",cols="2,2,2,2",options="header"]
|=======================================================================
| Application Example | Client Type | User interaction type | Recommended Flow
| Single Page Web Application for a Patient Portal | Public client | Patient facing | Authorization Code Flow with PKCE
| Mobile Application for tracking heart rate | Public client | Patient facing | Authorization Code Flow with PKCE
| Web Application with Backend for cardiology management | Confidential client | Practitioner facing | Authorization Code Flow with PKCE or Authorization Code Flow with Client Secret
| Realtime alert system for hospital | Confidential client | Backend | JWS Assertion Flow or Client Credentials Flow
|=======================================================================

The following flows are considered legacy and SHOULD NOT be used:

- {ietf_html}/rfc6749#section-1.3.2[Implicit Flow^]
- {ietf_html}/rfc6749#section-1.3.3[Resource Owner Password Credentials^]

== SMART Authorization Flow

Both Patient facing and Practitioner facing application have special requirements that cannot be fulfilled by standard OAuth2. These applications can be opened in one of two ways:

1. Standalone launch: The URL of the application is opened directly be the end user. Eg: `https://myapp.com`. The application decides which CDR url to use based on the user's selection.
2. Embedded EHR launch: The application is embedded within an EHR using an iFrame. Additional parameters are passed to the application to indicate the CDR to use, and the launch context. Eg: `https://myapp.com?launch=123&iss=https://cdr.com`


The Authorization Code Flow as defined in OAuth2 is a 2 step process where:

1. The client first requests an authorization code from the authorization server by redirecting the user to the `authorization_endpoint`.
2. Exchanges the authorization code for an access token by using the `token_endpoint`

The SMART protocol makes the following modifications to the Authorization Code Flow to enhance it for the use case of standalone and embedded launch:

=== Context Selection
In the Standalone launch, application can request a CDR for context selection. Most patient and practitioner facing application, along with the initial login and consent page, will also require the CDR to send additional context like the patient ID, Episode ID to the application. This context data can be used to pre-populate the application with the correct data.

The CDR can do this by automatically inferring the context based on the user logged in or `launch` token (in case of Embedded iFrame Launch). The CDR can provide a screen right after the consent page to select the context in case of ambuity.

The application can request the CDR for openEHR related context selection by passing the following special scopes in the authorization request:

[width="100%",cols="2,2",options="header"]
|=======================================================================
| Scope | Meaning
| `launch/patient` | When launching outside the EHR, ask for the openEHR EHR ID to be selected.
|=======================================================================

The context data populated by the EHR is returned in the token response along with the `id_token` and `access_token`. The following additional parameters are added to the token response:

[width="100%",cols="2,2",options="header"]
|=======================================================================
| Parameter | Meaning
| ehrId | UUID (string) of the openEHR EHR associated with the FHIR Patient resource in the launch.
|=======================================================================

The application can make use of these parameters to render the correct information to the user.

[NOTE]
====
The launch scopes and token attributes from SMART on FHIR can also be combined here for backward compatibility. All the parameters covered by SMART on FHIR is not covered here.
====

=== Embedded iFrame Launch
Most practitioner facing, as well as some patient facing applications will have to be embedded within the user's workflow by using an iFrame. The CDR can automatically select the correct context for the application by passing the `launch` parameter to the application's url. The CDR should also provide the `iss` parameter to indicate the CDR for the application to use.

The application will be opened on a URL like follows: `https://myapp.com?launch=123&iss=https://cdr.com`.

The application can then use the `iss` parameter to obtain the CDR configuration from the `.well-known/smart-configuration` endpoint. It then uses the `authorization_endpoint` to start the Authorization Code Flow. The `launch` parameter is passed along to the authorization request.

The following scope is also mandatory while passing the `launch` parameter:
[width="100%",cols="2,2",options="header"]
|=======================================================================
| Scope | Meaning
| `launch` | Permission to obtain launch context when app is launched from an EHR using launch parameter. This should be accompanied by an additional `launch` parameter in the authorization request.
|=======================================================================

It is **RECOMMENDED** that the `launch` token be a base64 encoded JSON object containing the context attributes like: `ehrId`, along with other attributes for internal purposes. The application can use this information to pre-populate the application without initiating an authorization request if it is already authenticated. This will enable a seamless experience for the user when switching between patients while using the application within an iFrame. This capability can be advertised by adding the `launch-base64-json` to the `capabilities` parameter of the `/.well-known/smart-configuration` response.


== Scopes for openEHR REST API
The application can request access to the CDR resources using the OAuth2.0 scopes. 

A complete scope is represented using:

`<compartment>/<resource>.<permission>`

The scopes are based on 3 different compartments:

- `patient/*`: These scopes are used when the EHR ID is present in the context. Only access to resources in the compartment of the EHR ID is allowed.
- `user/*`: These scopes are used when the user is identified by the CDR. It is usually a practitioner or an administrator. Only access to resources that the user would usually have access to is allowed.
- `system/*`: These scopes are used when the user is not available and the application is a backend confidential application. These scopes are obtained in advance while registering the application and provides unrestricted access to resources in the CDR.

The following resource expressions are supported:

- `template-<templateId>`: Templates which match the <templateId> expression.
- `composition-<templateId>`: Compositions of the templates which match the <templateId> expression.
- `aql-<queryName>`: AQL Queries that match the <queryName> expression. If the <queryName> is `*`, then all queries as well as ad-hoc queries are allowed.

The `<templateId>` in the above definition follows the blob pattern matching delimited by a `.` period. For example:

- `MyHospital.Template.v0` - Matches only `MyHospital.Template.v0`
- `*.Template.v0` - Matches `MyHospital.Template.v0` and `OtherHospital.Template.v0`
- `MyHospital.**` - Matches `MyHospital.Template.v0`, `MyHospital.Template.v2` and `MyHospital.OtherTemplate.v0`
- `*` - Matches all templates in the system

The <queryName> in the above definition follows the blob pattern matching delimited by “.” a period. For example:

- `org.openehr::compositions` - Matches only `org.openehr::compositions`
- `org.openehr::*` - Matches `org.openehr::compositions` and `org.openehr::bloodpressure`
- `org.openehr::**` - Matches `org.openehr::compositions`, `org.openehr::bloodpressure`, `org.openehr::bloodpressure.v1`
- `*` - Matches all queries and ad-hoc queries

The following permission expressions are supported:

- `c`: The ability to create a resource.
- `r`: The ability to read a resource.
- `u`: The ability to update a resource.
- `d`: The ability to delete a resource.
- `s`: The ability to search a resource. In case of `aql-<queryName>` scope, this means the ability to execute the query.

The following table is a maximal representation of the scopes made possible in different compartment/resource.permission combinations:

[width="100%",cols="2,2",options="header"]
|=======================================================================
| Scope | Meaning
|`patient/composition-<templateId>.crud` | Permission to create, read, update and delete compositions of `<templateId>` that are within the EHR of the patient in context.
|`user/composition-<templateId>.crud` | Permission to create, read, update and delete compositions of `<templateId>` that are within the EHRs the logged-in user has access to.
|`system/composition-<templateId>.crud` | Permission to create, read, update and delete compositions of `<templateId>` of all EHRs in the system.
|`patient/template-<templateId>.r` | Permission to read a template with `<templateId>`
|`user/template-<templateId>.crud` | Permission to create and read a template with `<templateId>`
|`system/template-<templateId>.crud` | Permission to create, read, update and delete a template with `<templateId>`
|`patient/aql-<queryName>.rs` | Permission to read and execute AQL with `<queryName>` on EHR ID of the patient in context.
|`user/aql-<queryName>.cruds` | Permission to create, read, update, delete and execute AQL with <queryName> on EHR IDs that the logged-in user has access to. If `<queryName>` is equal to the wildcard *, this scope will allow the ad-hoc query endpoint.
|`system/aql-<queryName>.cruds` | Permission to create, read, update, delete and execute AQL with `<queryName>`. If `<queryName>` is equal to the wildcard *, this scope will allow the ad-hoc query endpoint. 
|=======================================================================
