= Conceptual Approach

== Background

SMART stands for “Substitutable Medical Applications and Reusable Technologies” and was initially proposed as link:https://build.fhir.org/ig/HL7/smart-app-launch/index.html/[SMART on FHIR] which is a protocol which works on top of FHIR APIs. 

The specification builds on OAuth2 and OIDC which are industry standards for authentication and authorization, and allows 3rd party apps to seamlessly work with any EHR that implements the protocol.

The SMART on openEHR specification aims to be backward compatible with SMART on FHIR while making this protocol work for vendors utilizing openEHR, FHIR REST APIs, and more.

== Glossary

[width="100%",cols="2,2",options="header"]
|=======================================================================
|Term | Definition
|Vendor | An entity that provides software to end users.
|Application | Software developed by the vendor or an external entity designed to work with the CDR and/or Launcher built by the vendor.
|openEHR CDR | An openEHR Clinical Data Repository that provides a REST API conformant to the openEHR REST API specification.
|FHIR CDR | A FHIR server that provides an FHIR REST API conformant with the FHIR specification.
|OAuth2 Server | An authentication server that provides APIs consistent with the OAuth2 specification and will be extended to the SMART protocol that will be described in this document
|Launcher | User facing software built by the CDR vendor that serves to launch other applications within the user being a patient or practitioner. This could be the “EHR” that provides other functionality, but could also a separate application.
|=======================================================================

== Why SMART on openEHR?

It has long been recognized that a single vendor cannot provide all the necessary tools and software for a healthcare system while still maintaining a high level of quality and a low cost of ownership.Independent vendors who focus on a specific problem have an edge over monolithic "suites" of software that try to do everything. This is because they can focus on a specific problem and solve it well.

In practice, this requires applications from multiple vendors working together to provide a complete solution. The way that this is currently done is by long, tedious manual "integration" phase where the vendors work together to make their software work together. This is a very expensive process and is a major barrier to entry for new vendors.

The SMART specification aims to solve this problem by providing a standard way for vendors to work together. SMART defines a contract between the Application vendor and the CDR vendor that covers the following requirements:

- The Application should have the ability to be hosted on a domain owned by the Application vendor
- The CDR should have the ability to be hosted on a domain owned by the CDR vendor
- The Application needs a way to discovery API services offered by the CDR
- The Application needs a way to authenticate with the CDR to access the APIs offered by the CDR
- The Application needs a way to understand the "context" their app should open in by letting the CDR handle EHR and Episode selection
- The Application needs a way to embed within the CDR's user interface while maintaining the "context" to provide a seamless user experience