include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Sidharth Ramesh; Medblocks.
* Sebastian Iancu; Architect, Code24, Netherlands

=== Contributors

This specification has benefited from formal and informal input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following for their contributions.

* Ian McNicoll MD, FreshEHR, UK
* Bostjan Lah, Senior Architect, Better, Slovenia

A significant part of the design ideas of this specification was derived from:

* SMART App Launch - Release 2.1.0, published by HL7® FHIR® standard

=== Trademarks

* 'openEHR' is a registered trademark of the openEHR Foundation
* HL7® and FHIR® are the registered trademark of the Health Level Seven International and their use does not constitute endorsement by HL7
* SMART™ and the SMART logos are trademarks of The Children’s Medical Center Corporation. Used with permission.





[bibliography]

:sectnums!:

include::partial$amendment_record.adoc[]
