//
// Activity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Activity: Codable {

    public var timing: DvParsable?
    public var actionArchetypeId: String
    public var _description: ItemStructure

    public init(timing: DvParsable? = nil, actionArchetypeId: String, _description: ItemStructure) {
        self.timing = timing
        self.actionArchetypeId = actionArchetypeId
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case timing
        case actionArchetypeId = "action_archetype_id"
        case _description = "description"
    }

}
