//
// CareEntry.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CareEntry: Codable {

    public var _protocol: ItemStructure?
    public var guidelineId: ObjectRef?

    public init(_protocol: ItemStructure? = nil, guidelineId: ObjectRef? = nil) {
        self._protocol = _protocol
        self.guidelineId = guidelineId
    }

    public enum CodingKeys: String, CodingKey { 
        case _protocol = "protocol"
        case guidelineId = "guideline_id"
    }

}
