//
// CodePhrase.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CodePhrase: Codable {

    public var terminologyId: TerminologyId
    public var codeString: String
    public var preferredTerm: String?

    public init(terminologyId: TerminologyId, codeString: String, preferredTerm: String? = nil) {
        self.terminologyId = terminologyId
        self.codeString = codeString
        self.preferredTerm = preferredTerm
    }

    public enum CodingKeys: String, CodingKey { 
        case terminologyId = "terminology_id"
        case codeString = "code_string"
        case preferredTerm = "preferred_term"
    }

}
