//
// Composition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A COMPOSITION resource */

public struct Composition: Codable {

    public var language: CodePhrase
    public var territory: CodePhrase
    public var category: DvCodedText
    public var context: EventContext
    public var composer: PartyProxy
    public var content: [ContentItem]

    public init(language: CodePhrase, territory: CodePhrase, category: DvCodedText, context: EventContext, composer: PartyProxy, content: [ContentItem]) {
        self.language = language
        self.territory = territory
        self.category = category
        self.context = context
        self.composer = composer
        self.content = content
    }


}
