//
// Contribution.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A CONTRIBUTION resource */

public struct Contribution: Codable {

    public var uid: HierObjectId
    public var versions: [ObjectRef]
    public var audit: AuditDetails

    public init(uid: HierObjectId, versions: [ObjectRef], audit: AuditDetails) {
        self.uid = uid
        self.versions = versions
        self.audit = audit
    }


}
