//
// DvCodedText.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvCodedText: Codable {

    public var definingCode: CodePhrase

    public init(definingCode: CodePhrase) {
        self.definingCode = definingCode
    }

    public enum CodingKeys: String, CodingKey { 
        case definingCode = "defining_code"
    }

}
