//
// DvDate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvDate: Codable {

    public var value: Date

    public init(value: Date) {
        self.value = value
    }


}
