//
// DvEncapsulated.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvEncapsulated: Codable {

    public var type: String
    public var charset: CodePhrase?
    public var language: CodePhrase?

    public init(type: String, charset: CodePhrase? = nil, language: CodePhrase? = nil) {
        self.type = type
        self.charset = charset
        self.language = language
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "_type"
        case charset
        case language
    }

}
