//
// DvOrdered.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvOrdered: Codable {

    public var type: String?
    public var normalStatus: CodePhrase?
    public var normalRange: DvInterval?
    public var otherReferenceRanges: [ReferenceRange]?

    public init(type: String? = nil, normalStatus: CodePhrase? = nil, normalRange: DvInterval? = nil, otherReferenceRanges: [ReferenceRange]? = nil) {
        self.type = type
        self.normalStatus = normalStatus
        self.normalRange = normalRange
        self.otherReferenceRanges = otherReferenceRanges
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "_type"
        case normalStatus = "normal_status"
        case normalRange = "normal_range"
        case otherReferenceRanges = "other_reference_ranges"
    }

}
