//
// DvProportion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvProportion: Codable {

    public var numerator: Decimal
    public var denominator: Decimal
    public var semanticType: Int
    public var precision: Int?

    public init(numerator: Decimal, denominator: Decimal, semanticType: Int, precision: Int? = nil) {
        self.numerator = numerator
        self.denominator = denominator
        self.semanticType = semanticType
        self.precision = precision
    }

    public enum CodingKeys: String, CodingKey { 
        case numerator
        case denominator
        case semanticType = "semantic_type"
        case precision
    }

}
