//
// DvQuantity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvQuantity: Codable {

    public var magnitude: Decimal
    public var precision: Int?
    public var units: String
    public var unitsSystem: String?
    public var unitsDisplayName: String?

    public init(magnitude: Decimal, precision: Int? = nil, units: String, unitsSystem: String? = nil, unitsDisplayName: String? = nil) {
        self.magnitude = magnitude
        self.precision = precision
        self.units = units
        self.unitsSystem = unitsSystem
        self.unitsDisplayName = unitsDisplayName
    }

    public enum CodingKeys: String, CodingKey { 
        case magnitude
        case precision
        case units
        case unitsSystem = "units_system"
        case unitsDisplayName = "units_display_name"
    }

}
