//
// DvState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvState: Codable {

    public var type: String?
    public var value: DvCodedText
    public var isTerminal: Bool

    public init(type: String? = nil, value: DvCodedText, isTerminal: Bool) {
        self.type = type
        self.value = value
        self.isTerminal = isTerminal
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "_type"
        case value
        case isTerminal = "is_terminal"
    }

}
