//
// DvText.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvText: Codable {

    public var type: String?
    public var value: String
    public var hyperlink: DvUri?
    public var language: CodePhrase?
    public var encoding: CodePhrase?
    public var formatting: String?

    public init(type: String? = nil, value: String, hyperlink: DvUri? = nil, language: CodePhrase? = nil, encoding: CodePhrase? = nil, formatting: String? = nil) {
        self.type = type
        self.value = value
        self.hyperlink = hyperlink
        self.language = language
        self.encoding = encoding
        self.formatting = formatting
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "_type"
        case value
        case hyperlink
        case language
        case encoding
        case formatting
    }

}
