//
// DvTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DvTime: Codable {

    public var value: String

    public init(value: String) {
        self.value = value
    }


}
