//
// EhrStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An EHR_STATUS resource */

public struct EhrStatus: Codable {

    public var subject: PartyProxy
    public var isQueryable: Bool
    public var isModifiable: Bool
    public var otherDetails: ItemStructure?

    public init(subject: PartyProxy, isQueryable: Bool, isModifiable: Bool, otherDetails: ItemStructure? = nil) {
        self.subject = subject
        self.isQueryable = isQueryable
        self.isModifiable = isModifiable
        self.otherDetails = otherDetails
    }

    public enum CodingKeys: String, CodingKey { 
        case subject
        case isQueryable = "is_queryable"
        case isModifiable = "is_modifiable"
        case otherDetails = "other_details"
    }

}
