//
// Element.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Element: Codable {

    public var nullFlavour: DvCodedText?
    public var value: DataValue?
    public var nullReason: DvText?

    public init(nullFlavour: DvCodedText? = nil, value: DataValue? = nil, nullReason: DvText? = nil) {
        self.nullFlavour = nullFlavour
        self.value = value
        self.nullReason = nullReason
    }

    public enum CodingKeys: String, CodingKey { 
        case nullFlavour = "null_flavour"
        case value
        case nullReason = "null_reason"
    }

}
