//
// FeederAuditDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FeederAuditDetails: Codable {

    public var systemId: String
    public var location: PartyIdentified?
    public var subject: PartyProxy?
    public var provider: PartyIdentified?
    public var time: DvDateTime?
    public var versionId: String?
    public var otherDetails: ItemStructure?

    public init(systemId: String, location: PartyIdentified? = nil, subject: PartyProxy? = nil, provider: PartyIdentified? = nil, time: DvDateTime? = nil, versionId: String? = nil, otherDetails: ItemStructure? = nil) {
        self.systemId = systemId
        self.location = location
        self.subject = subject
        self.provider = provider
        self.time = time
        self.versionId = versionId
        self.otherDetails = otherDetails
    }

    public enum CodingKeys: String, CodingKey { 
        case systemId = "system_id"
        case location
        case subject
        case provider
        case time
        case versionId = "version_id"
        case otherDetails = "other_details"
    }

}
