//
// Folder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A FOLDER resource */

public struct Folder: Codable {

    public var items: [ObjectRef]?
    public var folders: [Folder]?
    public var details: ItemStructure?

    public init(items: [ObjectRef]? = nil, folders: [Folder]? = nil, details: ItemStructure? = nil) {
        self.items = items
        self.folders = folders
        self.details = details
    }


}
