//
// GenericId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GenericId: Codable {

    public var type: String?
    public var value: String
    public var scheme: String

    public init(type: String? = nil, value: String, scheme: String) {
        self.type = type
        self.value = value
        self.scheme = scheme
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "_type"
        case value
        case scheme
    }

}
