//
// InstructionDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InstructionDetails: Codable {

    public var type: String?
    public var instructionId: LocatableRef
    public var activityId: String
    public var wfDetails: ItemStructure?

    public init(type: String? = nil, instructionId: LocatableRef, activityId: String, wfDetails: ItemStructure? = nil) {
        self.type = type
        self.instructionId = instructionId
        self.activityId = activityId
        self.wfDetails = wfDetails
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "_type"
        case instructionId = "instruction_id"
        case activityId = "activity_id"
        case wfDetails = "wf_details"
    }

}
