//
// ItemList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ItemList: Codable {

    public var items: [Element]?

    public init(items: [Element]? = nil) {
        self.items = items
    }


}
