//
// ItemStructure.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ItemStructure: Codable {


    public init() {
    }


}
