//
// ItemSingle.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ItemSingle: Codable {

    public var item: Element

    public init(item: Element) {
        self.item = item
    }


}
