//
// ItemTree.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ItemTree: Codable {

    public var items: [Item]?

    public init(items: [Item]? = nil) {
        self.items = items
    }


}
