//
// ItemTable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ItemTable: Codable {

    public var items: [Clstr]?

    public init(items: [Clstr]? = nil) {
        self.items = items
    }


}
