//
// Link.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Link: Codable {

    public var meaning: DvText
    public var type: DvText
    public var target: DvEhrUri

    public init(meaning: DvText, type: DvText, target: DvEhrUri) {
        self.meaning = meaning
        self.type = type
        self.target = target
    }


}
