//
// LocatableRef.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LocatableRef: Codable {

    public var namespace: String
    public var type: String
    public var _id: UidBasedId
    public var path: String?

    public init(namespace: String, type: String, _id: UidBasedId, path: String? = nil) {
        self.namespace = namespace
        self.type = type
        self._id = _id
        self.path = path
    }

    public enum CodingKeys: String, CodingKey { 
        case namespace
        case type
        case _id = "id"
        case path
    }

}
