//
// NewContribution.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A new (un-committed) CONTRIBUTION resource */

public struct NewContribution: Codable {

    public var uid: HierObjectId?
    public var versions: [UpdateVersion]
    public var audit: UpdateAudit

    public init(uid: HierObjectId? = nil, versions: [UpdateVersion], audit: UpdateAudit) {
        self.uid = uid
        self.versions = versions
        self.audit = audit
    }


}
