//
// ObjectRef.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ObjectRef: Codable {

    public var namespace: String
    public var type: String
    public var _id: ObjectId

    public init(namespace: String, type: String, _id: ObjectId) {
        self.namespace = namespace
        self.type = type
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case namespace
        case type
        case _id = "id"
    }

}
