//
// Observation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Observation: Codable {

    public var data: History
    public var state: History?

    public init(data: History, state: History? = nil) {
        self.data = data
        self.state = state
    }


}
