//
// OriginalVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OriginalVersion: Codable {

    public var type: String?
    public var contribution: ObjectRef
    public var signature: String?
    public var commitAudit: AuditDetails
    public var data: Versionable
    public var uid: ObjectVersionId
    public var precedingVersionUid: ObjectVersionId?
    public var otherInputVersionUids: [ObjectVersionId]?
    public var lifecycleState: DvCodedText
    public var attestations: [Attestation]?

    public init(type: String? = nil, contribution: ObjectRef, signature: String? = nil, commitAudit: AuditDetails, data: Versionable, uid: ObjectVersionId, precedingVersionUid: ObjectVersionId? = nil, otherInputVersionUids: [ObjectVersionId]? = nil, lifecycleState: DvCodedText, attestations: [Attestation]? = nil) {
        self.type = type
        self.contribution = contribution
        self.signature = signature
        self.commitAudit = commitAudit
        self.data = data
        self.uid = uid
        self.precedingVersionUid = precedingVersionUid
        self.otherInputVersionUids = otherInputVersionUids
        self.lifecycleState = lifecycleState
        self.attestations = attestations
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "_type"
        case contribution
        case signature
        case commitAudit = "commit_audit"
        case data
        case uid
        case precedingVersionUid = "preceding_version_uid"
        case otherInputVersionUids = "other_input_version_uids"
        case lifecycleState = "lifecycle_state"
        case attestations
    }

}
