//
// TermMapping.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TermMapping: Codable {

    public var match: String
    public var purpose: DvCodedText?
    public var target: CodePhrase

    public init(match: String, purpose: DvCodedText? = nil, target: CodePhrase) {
        self.match = match
        self.purpose = purpose
        self.target = target
    }


}
