//
// TerminologyCode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TerminologyCode: Codable {

    public var terminologyId: String
    public var terminologyVersion: String?
    public var codeString: String
    public var uri: String?

    public init(terminologyId: String, terminologyVersion: String? = nil, codeString: String, uri: String? = nil) {
        self.terminologyId = terminologyId
        self.terminologyVersion = terminologyVersion
        self.codeString = codeString
        self.uri = uri
    }

    public enum CodingKeys: String, CodingKey { 
        case terminologyId = "terminology_id"
        case terminologyVersion = "terminology_version"
        case codeString = "code_string"
        case uri
    }

}
