//
// UpdateVersion.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UpdateVersion: Codable {

    public var precedingVersionUid: ObjectVersionId?
    public var signature: String?
    public var lifecycleState: TerminologyCode
    public var attestations: [UpdateAttestation]?
    public var data: Versionable
    public var commitAudit: UpdateAudit

    public init(precedingVersionUid: ObjectVersionId? = nil, signature: String? = nil, lifecycleState: TerminologyCode, attestations: [UpdateAttestation]? = nil, data: Versionable, commitAudit: UpdateAudit) {
        self.precedingVersionUid = precedingVersionUid
        self.signature = signature
        self.lifecycleState = lifecycleState
        self.attestations = attestations
        self.data = data
        self.commitAudit = commitAudit
    }

    public enum CodingKeys: String, CodingKey { 
        case precedingVersionUid = "preceding_version_uid"
        case signature
        case lifecycleState = "lifecycle_state"
        case attestations
        case data
        case commitAudit = "commit_audit"
    }

}
