//
// VersionedObject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct VersionedObject: Codable {

    public var type: String?
    public var uid: HierObjectId
    public var ownerId: ObjectRef
    public var timeCreated: DvDateTime

    public init(type: String? = nil, uid: HierObjectId, ownerId: ObjectRef, timeCreated: DvDateTime) {
        self.type = type
        self.uid = uid
        self.ownerId = ownerId
        self.timeCreated = timeCreated
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "_type"
        case uid
        case ownerId = "owner_id"
        case timeCreated = "time_created"
    }

}
