//
// Versionable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A Versionable resource */

public struct Versionable: Codable {


    public init() {
    }


}
