FORMAT: 1A
HOST: http://www.openehr.org/api/v1

# OpenEHR REST Definitions API

Release: **_Release_**

Status: **`TRIAL`**

<!-- include(includes/overview.apib) -->

# Group Definitions 

This is a collection of resources to manage the clinical definitions and models of the openEHR Server. 
They allow management of openEHR templates and queries. 

<!-- include(includes/template.apib) -->

<!-- include(includes/query_definition.apib) -->
