FORMAT: 1A
HOST: http://www.openehr.org/api/v1
RELEASE: 1.0.1
STATUS: TRIAL

# OpenEHR REST Definitions API

<h3>Amendment Record</h3>

| Issue | Details | Raiser, Implementer | Completed
|-------|---------|---------------------|-----------|
| 1.0.1 | Update links | S Iancu | 16 Dec 2018
| 1.0.0 | [Release-1.0.0](https://specifications.openehr.org/releases/ITS-REST/Release-1.0.0) | Specifications Editorial Committee (SEC) | 07 Dec 2018


<!-- include(includes/overview.apib) -->

# Group Definitions 

This is a collection of resources to manage the clinical definitions and models of the openEHR Server. 
They allow management of openEHR templates and queries. 

<!-- include(includes/template.apib) -->

<!-- include(includes/query_definition.apib) -->
