FORMAT: 1A
HOST: {baseUrl}/v1
API: definition
RELEASE: 1.1.0
STATUS: TRIAL

# Definitions API

<!-- include(includes/copyright.html) -->

<h3>Amendment Record</h3>

| Issue | Details | Raiser, Implementer | Completed
|-------|---------|---------------------|-----------|
| 1.1.0 | [SPECITS-24](https://specifications.openehr.org/tickets/SPECITS-24): Added changelog | J Smolka, S Iancu | 12 May 2019
| 1.0.1 | Update links | S Iancu | 16 Dec 2018
| 1.0.0 | [Release-1.0.0](https://specifications.openehr.org/releases/ITS-REST/Release-1.0.0) | Specifications Editorial Committee (SEC) | 07 Dec 2018


# Group Definitions 

This is a collection of resources to manage the clinical definitions and models of the openEHR Server. 
They allow management of openEHR templates and queries. 

<!-- include(includes/template.apib) -->

<!-- include(includes/query_definition.apib) -->
