FORMAT: 1A
HOST: {baseUrl}/v1
API: query
RELEASE: 1.1.0
STATUS: TRIAL

# Query API

<!-- include(includes/copyright.html) -->

<h3>Amendment Record</h3>

| Issue | Details | Raiser, Implementer | Completed
|-------|---------|---------------------|-----------|
| 1.1.0 | [SPECITS-24](https://specifications.openehr.org/tickets/SPECITS-24): Added changelog | J Smolka, S Iancu | 12 May 2019
| 1.0.1 | Update links | S Iancu | 16 Dec 2018
| 1.0.0 | [Release-1.0.0](https://specifications.openehr.org/releases/ITS-REST/Release-1.0.0) | Specifications Editorial Committee (SEC) | 07 Dec 2018


<!-- include(includes/query_overview.apib) -->

# Group Query
The REST API currently supports AQL queries. Other query types might be added at a later time. 

<!-- include(includes/query.apib) -->
