FORMAT: 1A
HOST: {baseUrl}/v1
API: query
RELEASE: latest
STATUS: STABLE

# Query API

<!-- include(includes/copyright.html) -->

<h3>Amendment Record</h3>

<!-- include(includes/changelogs/query.html) -->

<!-- include(includes/query_overview.apib) -->

# Group Query

Actions upon resources of this group are also formally described in the 
[I_QUERY_SERVICE](https://specifications.openehr.org/releases/SM/latest/openehr_platform.html#_i_query_service_interface)
Abstract Service Model interface.

<!-- include(includes/query.apib) -->
