FORMAT: 1A
HOST: http://www.openehr.org/api/v1
RELEASE: 1.0.1
STATUS: TRIAL

# OpenEHR REST Query API

<h3>Amendment Record</h3>

| Issue | Details | Raiser, Implementer | Completed
|-------|---------|---------------------|-----------|
| 1.0.1 | Update links | S Iancu | 16 Dec 2018
| 1.0.0 | [Release-1.0.0](https://specifications.openehr.org/releases/ITS-REST/Release-1.0.0) | Specifications Editorial Committee (SEC) | 07 Dec 2018


<!-- include(includes/query_overview.apib) -->

# Group Query
The REST API currently supports AQL queries. Other query types might be added at a later time. 

<!-- include(includes/query.apib) -->
