//
// CONTRIBUTIONAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class CONTRIBUTIONAPI {
    /**
     * enum for parameter prefer
     */
    public enum Prefer_contributionCreate: String { 
        case representation = "return=representation"
        case minimal = "return=minimal"
    }

    /**
     Create CONTRIBUTION

     - parameter body: (body) The CONTRIBUTION.
 
     - parameter ehrId: (path) EHR identifier taken from EHR.ehr_id.value.  
     - parameter prefer: (header) Request header to indicate the preference over response details. The response will contain the entire resource when the &#x60;Prefer&#x60; header has a value of &#x60;return&#x3D;representation&#x60;.  (optional, default to return=minimal)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func contributionCreate(body: NewContribution, ehrId: String, prefer: Prefer_contributionCreate? = nil, completion: @escaping ((_ data: Contribution?,_ error: Error?) -> Void)) {
        contributionCreateWithRequestBuilder(body: body, ehrId: ehrId, prefer: prefer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create CONTRIBUTION
     - POST /ehr/{ehr_id}/contribution

     - responseHeaders: [ETag(String), Location(String)]
     - responseHeaders: [ETag(String), Location(String)]
     - examples: [{contentType=application/json, example={
  "uid" : {
    "value" : "0826851c-c4c2-4d61-92b9-410fb8275ff0"
  },
  "versions" : [ {
    "_type" : "OBJECT_REF",
    "id" : {
      "_type" : "OBJECT_VERSION_ID",
      "value" : "fb458d9c-1323-42bc-b7f8-787f3660a0b5::openEHRSys.example.com::1"
    },
    "namespace" : "local",
    "type" : "COMPOSITION"
  }, {
    "_type" : "OBJECT_REF",
    "id" : {
      "_type" : "OBJECT_VERSION_ID",
      "value" : "abcdefgh-1323-42bc-b7f8-787f3660a0ba::openEHRSys.example.com::1"
    },
    "namespace" : "local",
    "type" : "FOLDER"
  } ],
  "audit" : {
    "system_id" : "9624982A-9F42-41A5-9318-AE13D5F5031F",
    "committer" : {
      "_type" : "PARTY_IDENTIFIED",
      "name" : "A user name"
    },
    "time_committed" : {
      "value" : "2017-08-15T10:37:15.422+02:00"
    },
    "change_type" : {
      "value" : "creation",
      "defining_code" : {
        "terminology_id" : {
          "value" : "openehr"
        },
        "code_string" : "249"
      }
    },
    "description" : {
      "value" : "Description text"
    }
  }
}}]
     - parameter body: (body) The CONTRIBUTION.
 
     - parameter ehrId: (path) EHR identifier taken from EHR.ehr_id.value.  
     - parameter prefer: (header) Request header to indicate the preference over response details. The response will contain the entire resource when the &#x60;Prefer&#x60; header has a value of &#x60;return&#x3D;representation&#x60;.  (optional, default to return=minimal)

     - returns: RequestBuilder<Contribution> 
     */
    open class func contributionCreateWithRequestBuilder(body: NewContribution, ehrId: String, prefer: Prefer_contributionCreate? = nil) -> RequestBuilder<Contribution> {
        var path = "/ehr/{ehr_id}/contribution"
        let ehrIdPreEscape = "\(ehrId)"
        let ehrIdPostEscape = ehrIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{ehr_id}", with: ehrIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
                        "Prefer": prefer?.rawValue
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<Contribution>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }
    /**
     Get CONTRIBUTION by id

     - parameter ehrId: (path) EHR identifier taken from EHR.ehr_id.value.  
     - parameter contributionUid: (path) The CONTRIBUTION uid.  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func contributionGet(ehrId: String, contributionUid: String, completion: @escaping ((_ data: Contribution?,_ error: Error?) -> Void)) {
        contributionGetWithRequestBuilder(ehrId: ehrId, contributionUid: contributionUid).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get CONTRIBUTION by id
     - GET /ehr/{ehr_id}/contribution/{contribution_uid}

     - examples: [{contentType=application/json, example={
  "uid" : {
    "value" : "0826851c-c4c2-4d61-92b9-410fb8275ff0"
  },
  "versions" : [ {
    "_type" : "OBJECT_REF",
    "id" : {
      "_type" : "OBJECT_VERSION_ID",
      "value" : "fb458d9c-1323-42bc-b7f8-787f3660a0b5::openEHRSys.example.com::1"
    },
    "namespace" : "local",
    "type" : "COMPOSITION"
  }, {
    "_type" : "OBJECT_REF",
    "id" : {
      "_type" : "OBJECT_VERSION_ID",
      "value" : "abcdefgh-1323-42bc-b7f8-787f3660a0ba::openEHRSys.example.com::1"
    },
    "namespace" : "local",
    "type" : "FOLDER"
  } ],
  "audit" : {
    "system_id" : "9624982A-9F42-41A5-9318-AE13D5F5031F",
    "committer" : {
      "_type" : "PARTY_IDENTIFIED",
      "name" : "A user name"
    },
    "time_committed" : {
      "value" : "2017-08-15T10:37:15.422+02:00"
    },
    "change_type" : {
      "value" : "creation",
      "defining_code" : {
        "terminology_id" : {
          "value" : "openehr"
        },
        "code_string" : "249"
      }
    },
    "description" : {
      "value" : "Description text"
    }
  }
}}]
     - parameter ehrId: (path) EHR identifier taken from EHR.ehr_id.value.  
     - parameter contributionUid: (path) The CONTRIBUTION uid.  

     - returns: RequestBuilder<Contribution> 
     */
    open class func contributionGetWithRequestBuilder(ehrId: String, contributionUid: String) -> RequestBuilder<Contribution> {
        var path = "/ehr/{ehr_id}/contribution/{contribution_uid}"
        let ehrIdPreEscape = "\(ehrId)"
        let ehrIdPostEscape = ehrIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{ehr_id}", with: ehrIdPostEscape, options: .literal, range: nil)
        let contributionUidPreEscape = "\(contributionUid)"
        let contributionUidPostEscape = contributionUidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{contribution_uid}", with: contributionUidPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Contribution>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
