= Simplified Reference Model (SRM)

== Overview

The Simplified Reference Model (SRM) is a version of the canonical Reference Model (RM) that contains structurally simpler representations of many class attributes, enabling easier construction of string-oriented serialisations such as JSON, compared to the full canonical structures. The SRM is defined as a set of classes named after a sub-set of RM classes, with `S_` prepended; for example, in the SRM, the RM class `ELEMENT` becomes `S_ELEMENT`. Each `S_XXX` class has a constructor `_from_rm (an_rm_obj: Any)_` that can be used to create an instance from a canonical object, and aso a factory routine `_to_rm (rm: BMM_MODEL): Any_`, which can regenerate an canonical RM object from the `S_XXX` instance, with the help of a formal represntation of the RM (`_rm_` argument).

Various kinds of simpilifications are used in the SRM classes, including:

* String representation of some fields that are structured in the RM, e.g `CODE_PHRASE._terminology_id_` is of type `TERMINOLOGY_ID` but in the SRM, it is a `String`;
* replacing fully expressed `DV_CODED_TEXT` or `CODE_PHRASE` fields that represent codes from openEHR or other fixed (e.g. IANA media type) vocabularies which are determinable from the openEHR RM, with Strings;
* compressing fields of some sub-part objects into a parent object in the simplified version, reducing the need for long paths, e.g. `S_PARTY_PROXY` includes fields from `PARTY_PROXY._external_ref_`, of type `PARTY_REF`.

The cost of doing the above is that some work has to be done to convert an `S_XXX` instance into an `XXX` canonical instance, in some cases, requiring the use of a formal representation of the RM. In openEHR, this is available in the form of a BMM model, as described in the {openehr_lang_latest_bmm}[openEHR Basic-Meta Model specification^]. Additionally, some fields in data have to be parsed with various micro-parsers, e.g. for Date/Time.

The subset of RM classes for which SRM classes are defined is limited to the class `COMPOSITION` and classes reachable from it, or approximately 45 classes. Almost all simplifications are defined in near-leaf classes such as the `S_DATA_VALUE` descendants, `PARTICIPATION` and so on; classes such as `S_ENTRY` and `S_COMPOSITION` are largely structured the same way as in the canonical RM, except that sub-parts are of type `S_XXX` rather than `XXX`, where the latter is an original RM type. The exception to this is replacement of coded fields whose vocabulary is defined in the RM.

== Simplified RM Package

The following UML diagram shows the top-level `simplified_rm` package defining the special interface type `S_TYPE`.

[.text-center]
.`sm.simplified_rm` package
image::{uml_diagrams_uri}/SM-simplified_rm.svg[id=sm_simplified_rm, align="center"]

=== Class Definitions

include::{uml_export_dir}/classes/s_type.adoc[]

== Composition Package

The following UML diagram shows the top-level SRM `composition` package defining `S_COMPOSITION`, `S_SECTION` and the `S_ENTRY` types.

[.text-center]
.`sm.simplified_rm.composition` package
image::{uml_diagrams_uri}/SM-simplified_rm.composition.svg[id=sm_simplified_rm_composition, align="center"]

=== Class Definitions

include::{uml_export_dir}/classes/s_composition.adoc[]
include::{uml_export_dir}/classes/s_event_context.adoc[]
include::{uml_export_dir}/classes/s_content_item.adoc[]
include::{uml_export_dir}/classes/s_section.adoc[]
include::{uml_export_dir}/classes/s_entry.adoc[]
include::{uml_export_dir}/classes/s_admin_entry.adoc[]
include::{uml_export_dir}/classes/s_care_entry.adoc[]
include::{uml_export_dir}/classes/s_observation.adoc[]
include::{uml_export_dir}/classes/s_evaluation.adoc[]
include::{uml_export_dir}/classes/s_instruction.adoc[]
include::{uml_export_dir}/classes/s_activity.adoc[]
include::{uml_export_dir}/classes/s_action.adoc[]

== Common Package

The following UML diagram shows the SRM `common` package defining `S_XXX` types corresponding to the RM `rm.common` package types.

[.text-center]
.`sm.simplified_rm.common` package
image::{uml_diagrams_uri}/SM-simplified_rm.common.svg[id=sm_simplified_rm_common, align="center"]

=== Class Definitions

include::{uml_export_dir}/classes/s_locatable.adoc[]
include::{uml_export_dir}/classes/s_archetyped.adoc[]
include::{uml_export_dir}/classes/s_link.adoc[]
include::{uml_export_dir}/classes/s_feeder_audit.adoc[]
include::{uml_export_dir}/classes/s_feeder_audit_details.adoc[]
include::{uml_export_dir}/classes/s_party_proxy.adoc[]
include::{uml_export_dir}/classes/s_party_identified.adoc[]
include::{uml_export_dir}/classes/s_participation.adoc[]
include::{uml_export_dir}/classes/s_participation_identified.adoc[]

== Data Structures Package

The following UML diagram shows the SRM `data_structures` package defining `S_XXX` types corresponding to the RM `rm.data_structures` package types.

[.text-center]
.`sm.simplified_rm.data_structures` package
image::{uml_diagrams_uri}/SM-simplified_rm.data_structures.svg[id=sm_simplified_rm_data_structures, align="center"]

=== Class Definitions

include::{uml_export_dir}/classes/s_history.adoc[]
include::{uml_export_dir}/classes/s_event.adoc[]
include::{uml_export_dir}/classes/s_point_event.adoc[]
include::{uml_export_dir}/classes/s_interval_event.adoc[]
include::{uml_export_dir}/classes/s_item.adoc[]
include::{uml_export_dir}/classes/s_cluster.adoc[]
include::{uml_export_dir}/classes/s_element.adoc[]

== Data types Package

The following UML diagram shows the SRM `data_types` package defining `S_XXX` types corresponding to the RM `rm.data_types` package types.

[.text-center]
.`sm.simplified_rm.data_types` package
image::{uml_diagrams_uri}/SM-simplified_rm.data_types.svg[id=sm_simplified_rm_data_types, align="center"]

=== Class Definitions

include::{uml_export_dir}/classes/s_data_value.adoc[]
include::{uml_export_dir}/classes/s_dv_identifier.adoc[]

include::{uml_export_dir}/classes/s_dv_text.adoc[]
include::{uml_export_dir}/classes/s_dv_coded_text.adoc[]
include::{uml_export_dir}/classes/s_code_phrase.adoc[]

include::{uml_export_dir}/classes/s_dv_parsable.adoc[]

include::{uml_export_dir}/classes/s_dv_quantity.adoc[]
include::{uml_export_dir}/classes/s_dv_count.adoc[]
include::{uml_export_dir}/classes/s_dv_proportion.adoc[]
include::{uml_export_dir}/classes/s_dv_ordinal.adoc[]

