= Preface

== Purpose

This document describes various JSON data formats based on the openEHR Reference Model and Archetype Model, intended to be easier to use than the canonical formats, for typical developers with minimal exposure to openEHR. These formats are designed to enable easier creation of openEHR content (i.e. Compositions etc).

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_json_commit_formats}[{openehr_json_commit_formats}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

xxx

== Tooling

xxx
